from models.games import *
from models.teams import *
from lookups import *
from google.appengine.ext import db

class LoadGames:

    def __init__(self):
        self.load()

    def num_transactions(self):
        return len(self.transactions)

    def run_transactions(self,txn_range):
        last_index = self.num_transactions() - 1
        for i in txn_range:
            if i > last_index:
                break
            d = self.transactions[i]
            self.add_game(d)

    def __lookup_team(self,team):
        q = db.GqlQuery('SELECT * FROM Team WHERE name=:name',name=team)
        assert q
        assert q.count() == 1,"Error! name=%s, count=%d" % (team,q.count())
        return q[0]

    def add_game(self,game):
        g = Game()
        g.number = game['number']
        g.away_team = self.__lookup_team(game['away'])
        g.home_team = self.__lookup_team(game['home'])
        g.away_score = game['away_score']
        g.home_score = game['home_score']
        g.favored = game['favored']
        g.spread = game['spread']
        g.state = game['state']
        g.quarter = ''
        g.time_left = ''
        g.date = None
        key = g.put()
        l = Lookup(name='game',recno=game['recno'],instance_key=str(key))
        l.put()

    def load(self):
        self.transactions = []
        self.transactions.append({'recno':1,'number':1,'away':'South Carolina', 'home':'Vanderbilt', 'away_score':17, 'home_score':13, 'favored':'away','spread':7.5,'state':'final'})
        self.transactions.append({'recno':2,'number':2,'away':'Northwestern', 'home':'Syracuse', 'away_score':42, 'home_score':41, 'favored':'away','spread':1.5,'state':'final'})
        self.transactions.append({'recno':3,'number':3,'away':'Tennessee', 'home':'NC State', 'away_score':35, 'home_score':21, 'favored':'away','spread':3.5,'state':'final'})
        self.transactions.append({'recno':4,'number':4,'away':'Boise State', 'home':'Michigan State', 'away_score':13, 'home_score':17, 'favored':'home','spread':6.5,'state':'final'})
        self.transactions.append({'recno':5,'number':5,'away':'Miami-Florida', 'home':'Boston College', 'away_score':41, 'home_score':32, 'favored':'away','spread':0.5,'state':'final'})
        self.transactions.append({'recno':6,'number':6,'away':'Colorado State', 'home':'Colorado', 'away_score':22, 'home_score':17, 'favored':'home','spread':6.5,'state':'final'})
        self.transactions.append({'recno':7,'number':7,'away':'Kentucky', 'home':'Louisville', 'away_score':14, 'home_score':32, 'favored':'home','spread':13.5,'state':'final'})
        self.transactions.append({'recno':8,'number':8,'away':'Georgia Tech', 'home':'Virginia Tech', 'away_score':17, 'home_score':20, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':9,'number':9,'away':'Michigan', 'home':'Alabama', 'away_score':14, 'home_score':41, 'favored':'home','spread':13.5,'state':'final'})
        self.transactions.append({'recno':10,'number':10,'away':'Clemson', 'home':'Auburn', 'away_score':26, 'home_score':19, 'favored':'away','spread':3.5,'state':'final'})
        self.transactions.append({'recno':11,'number':1,'away':'Penn State', 'home':'Virginia', 'away_score':16, 'home_score':17, 'favored':'home','spread':10.5,'state':'final'})
        self.transactions.append({'recno':12,'number':2,'away':'Miami-Florida', 'home':'Kansas State', 'away_score':13, 'home_score':52, 'favored':'home','spread':6.5,'state':'final'})
        self.transactions.append({'recno':13,'number':3,'away':'Auburn', 'home':'Mississippi State', 'away_score':10, 'home_score':28, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':14,'number':4,'away':'North Carolina', 'home':'Wake Forest', 'away_score':27, 'home_score':28, 'favored':'away','spread':8.5,'state':'final'})
        self.transactions.append({'recno':15,'number':5,'away':'Florida', 'home':'Texas A&M', 'away_score':20, 'home_score':17, 'favored':'home','spread':1.5,'state':'final'})
        self.transactions.append({'recno':16,'number':6,'away':'Iowa State', 'home':'Iowa', 'away_score':9, 'home_score':6, 'favored':'home','spread':4.5,'state':'final'})
        self.transactions.append({'recno':17,'number':7,'away':'Wisconsin', 'home':'Oregon State', 'away_score':7, 'home_score':10, 'favored':'away','spread':8.5,'state':'final'})
        self.transactions.append({'recno':18,'number':8,'away':'Nebraska', 'home':'UCLA', 'away_score':30, 'home_score':36, 'favored':'away','spread':5.5,'state':'final'})
        self.transactions.append({'recno':19,'number':9,'away':'Illinois', 'home':'Arizona State', 'away_score':14, 'home_score':45, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':20,'number':10,'away':'Georgia', 'home':'Missouri', 'away_score':41, 'home_score':20, 'favored':'away','spread':3.5,'state':'final'})
        self.transactions.append({'recno':21,'number':1,'away':'Rutgers', 'home':'South Florida', 'away_score':23, 'home_score':13, 'favored':'home','spread':9.5,'state':'final'})
        self.transactions.append({'recno':22,'number':2,'away':'California', 'home':'Ohio State', 'away_score':28, 'home_score':35, 'favored':'home','spread':17.5,'state':'final'})
        self.transactions.append({'recno':23,'number':3,'away':'Texas', 'home':'Mississippi', 'away_score':66, 'home_score':31, 'favored':'away','spread':10.5,'state':'final'})
        self.transactions.append({'recno':24,'number':4,'away':'North Carolina', 'home':'Louisville', 'away_score':34, 'home_score':39, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':25,'number':5,'away':'Virginia', 'home':'Georgia Tech', 'away_score':20, 'home_score':56, 'favored':'home','spread':10.5,'state':'final'})
        self.transactions.append({'recno':26,'number':6,'away':'Florida', 'home':'Tennessee', 'away_score':37, 'home_score':20, 'favored':'home','spread':2.5,'state':'final'})
        self.transactions.append({'recno':27,'number':7,'away':'Arizona State', 'home':'Missouri', 'away_score':20, 'home_score':24, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':28,'number':8,'away':'Southern Cal', 'home':'Stanford', 'away_score':14, 'home_score':21, 'favored':'away','spread':10.5,'state':'final'})
        self.transactions.append({'recno':29,'number':9,'away':'Virginia Tech', 'home':'Pittsburgh', 'away_score':17, 'home_score':35, 'favored':'away','spread':12.5,'state':'final'})
        self.transactions.append({'recno':30,'number':10,'away':'Notre Dame', 'home':'Michigan State', 'away_score':20, 'home_score':3, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':31,'number':1,'away':'BYU', 'home':'Boise State', 'away_score':6, 'home_score':7, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':32,'number':2,'away':'Miami-Florida', 'home':'Georgia Tech', 'away_score':42, 'home_score':36, 'favored':'home','spread':13.5,'state':'final'})
        self.transactions.append({'recno':33,'number':3,'away':'Michigan', 'home':'Notre Dame', 'away_score':6, 'home_score':13, 'favored':'home','spread':6.5,'state':'final'})
        self.transactions.append({'recno':34,'number':4,'away':'Rutgers', 'home':'Arkansas', 'away_score':35, 'home_score':26, 'favored':'home','spread':5.5,'state':'final'})
        self.transactions.append({'recno':35,'number':5,'away':'Kansas State', 'home':'Oklahoma', 'away_score':24, 'home_score':19, 'favored':'home','spread':13.5,'state':'final'})
        self.transactions.append({'recno':36,'number':6,'away':'Missouri', 'home':'South Carolina', 'away_score':10, 'home_score':31, 'favored':'home','spread':9.5,'state':'final'})
        self.transactions.append({'recno':37,'number':7,'away':'Utah', 'home':'Arizona State', 'away_score':7, 'home_score':37, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':38,'number':8,'away':'Baylor', 'home':'Louisiana Monroe', 'away_score':47, 'home_score':42, 'favored':'away','spread':7.5,'state':'final'})
        self.transactions.append({'recno':39,'number':9,'away':'Oregon State', 'home':'UCLA', 'away_score':27, 'home_score':20, 'favored':'home','spread':11.5,'state':'final'})
        self.transactions.append({'recno':40,'number':10,'away':'Clemson', 'home':'Florida State', 'away_score':37, 'home_score':49, 'favored':'home','spread':13.5,'state':'final'})
        self.transactions.append({'recno':41,'number':1,'away':'Stanford', 'home':'Washington', 'away_score':13, 'home_score':17, 'favored':'away','spread':7.5,'state':'final'})
        self.transactions.append({'recno':42,'number':2,'away':'Tennessee', 'home':'Georgia', 'away_score':44, 'home_score':51, 'favored':'home','spread':14.5,'state':'final'})
        self.transactions.append({'recno':43,'number':3,'away':'Baylor', 'home':'West Virginia', 'away_score':63, 'home_score':70, 'favored':'home','spread':13.5,'state':'final'})
        self.transactions.append({'recno':44,'number':4,'away':'Ohio State', 'home':'Michigan State', 'away_score':17, 'home_score':16, 'favored':'home','spread':2.5,'state':'final'})
        self.transactions.append({'recno':45,'number':5,'away':'NC State', 'home':'Miami-Florida', 'away_score':37, 'home_score':44, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':46,'number':6,'away':'Arkansas', 'home':'Texas A&M', 'away_score':10, 'home_score':58, 'favored':'home','spread':13.5,'state':'final'})
        self.transactions.append({'recno':47,'number':7,'away':'Oregon State', 'home':'Arizona', 'away_score':38, 'home_score':35, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':48,'number':8,'away':'Clemson', 'home':'Boston College', 'away_score':45, 'home_score':31, 'favored':'away','spread':9.5,'state':'final'})
        self.transactions.append({'recno':49,'number':9,'away':'Duke', 'home':'Wake Forest', 'away_score':34, 'home_score':27, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':50,'number':10,'away':'Texas', 'home':'Oklahoma State', 'away_score':41, 'home_score':36, 'favored':'away','spread':2.5,'state':'final'})
        self.transactions.append({'recno':51,'number':1,'away':'Pittsburgh', 'home':'Syracuse', 'away_score':13, 'home_score':14, 'favored':'away','spread':2.5,'state':'final'})
        self.transactions.append({'recno':52,'number':2,'away':'Virginia Tech', 'home':'North Carolina', 'away_score':34, 'home_score':48, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':53,'number':3,'away':'UCLA', 'home':'California', 'away_score':17, 'home_score':43, 'favored':'away','spread':2.5,'state':'final'})
        self.transactions.append({'recno':54,'number':4,'away':'LSU', 'home':'Florida', 'away_score':6, 'home_score':14, 'favored':'away','spread':2.5,'state':'final'})
        self.transactions.append({'recno':55,'number':5,'away':'Georgia Tech', 'home':'Clemson', 'away_score':31, 'home_score':47, 'favored':'home','spread':9.5,'state':'final'})
        self.transactions.append({'recno':56,'number':6,'away':'Oklahoma', 'home':'Texas Tech', 'away_score':41, 'home_score':20, 'favored':'away','spread':3.5,'state':'final'})
        self.transactions.append({'recno':57,'number':7,'away':'Michigan', 'home':'Purdue', 'away_score':44, 'home_score':13, 'favored':'away','spread':3.5,'state':'final'})
        self.transactions.append({'recno':58,'number':8,'away':'West Virginia', 'home':'Texas', 'away_score':48, 'home_score':45, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':59,'number':9,'away':'Nebraska', 'home':'Ohio State', 'away_score':38, 'home_score':63, 'favored':'home','spread':4.5,'state':'final'})
        self.transactions.append({'recno':60,'number':10,'away':'Georgia', 'home':'South Carolina', 'away_score':7, 'home_score':35, 'favored':'home','spread':2.5,'state':'final'})
        self.transactions.append({'recno':61,'number':1,'away':'Oregon State', 'home':'BYU', 'away_score':42, 'home_score':24, 'favored':'home','spread':2.5,'state':'final'})
        self.transactions.append({'recno':62,'number':2,'away':'West Virginia', 'home':'Texas Tech', 'away_score':14, 'home_score':49, 'favored':'away','spread':4.5,'state':'final'})
        self.transactions.append({'recno':63,'number':3,'away':'Florida', 'home':'Vanderbilt', 'away_score':31, 'home_score':17, 'favored':'away','spread':7.5,'state':'final'})
        self.transactions.append({'recno':64,'number':4,'away':'South Carolina', 'home':'LSU', 'away_score':21, 'home_score':23, 'favored':'home','spread':2.5,'state':'final'})
        self.transactions.append({'recno':65,'number':5,'away':'Tennessee', 'home':'Mississippi State', 'away_score':31, 'home_score':41, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':66,'number':6,'away':'Texas A&M', 'home':'Louisiana Tech', 'away_score':59, 'home_score':57, 'favored':'away','spread':7.5,'state':'final'})
        self.transactions.append({'recno':67,'number':7,'away':'Maryland', 'home':'Virginia', 'away_score':27, 'home_score':20, 'favored':'home','spread':2.5,'state':'final'})
        self.transactions.append({'recno':68,'number':8,'away':'Stanford', 'home':'Notre Dame', 'away_score':13, 'home_score':20, 'favored':'home','spread':9.5,'state':'final'})
        self.transactions.append({'recno':69,'number':9,'away':'Wisconsin', 'home':'Purdue', 'away_score':38, 'home_score':14, 'favored':'home','spread':0.5,'state':'final'})
        self.transactions.append({'recno':70,'number':10,'away':'Texas', 'home':'Oklahoma', 'away_score':21, 'home_score':63, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':71,'number':1,'away':'Oregon', 'home':'Arizona State', 'away_score':43, 'home_score':21, 'favored':'away','spread':9.5,'state':'final'})
        self.transactions.append({'recno':72,'number':2,'away':'Nebraska', 'home':'Northwestern', 'away_score':29, 'home_score':28, 'favored':'away','spread':4.5,'state':'final'})
        self.transactions.append({'recno':73,'number':3,'away':'Florida State', 'home':'Miami-Florida', 'away_score':33, 'home_score':20, 'favored':'away','spread':12.5,'state':'final'})
        self.transactions.append({'recno':74,'number':4,'away':'Virginia Tech', 'home':'Clemson', 'away_score':17, 'home_score':38, 'favored':'home','spread':8.5,'state':'final'})
        self.transactions.append({'recno':75,'number':5,'away':'Michigan State', 'home':'Michigan', 'away_score':10, 'home_score':12, 'favored':'home','spread':10.5,'state':'final'})
        self.transactions.append({'recno':76,'number':6,'away':'Penn State', 'home':'Iowa', 'away_score':38, 'home_score':14, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':77,'number':7,'away':'LSU', 'home':'Texas A&M', 'away_score':24, 'home_score':19, 'favored':'away','spread':3.5,'state':'final'})
        self.transactions.append({'recno':78,'number':8,'away':'Kansas State', 'home':'West Virginia', 'away_score':55, 'home_score':14, 'favored':'home','spread':2.5,'state':'final'})
        self.transactions.append({'recno':79,'number':9,'away':'Texas Tech', 'home':'TCU', 'away_score':56, 'home_score':53, 'favored':'away','spread':2.5,'state':'final'})
        self.transactions.append({'recno':80,'number':10,'away':'South Carolina', 'home':'Florida', 'away_score':11, 'home_score':44, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':81,'number':1,'away':'Clemson', 'home':'Wake Forest', 'away_score':42, 'home_score':13, 'favored':'away','spread':12.5,'state':'final'})
        self.transactions.append({'recno':82,'number':2,'away':'Cincinnati', 'home':'Louisville', 'away_score':31, 'home_score':34, 'favored':'home','spread':4.5,'state':'final'})
        self.transactions.append({'recno':83,'number':3,'away':'Tennessee', 'home':'South Carolina', 'away_score':35, 'home_score':38, 'favored':'home','spread':14.5,'state':'final'})
        self.transactions.append({'recno':84,'number':4,'away':'Duke', 'home':'Florida State', 'away_score':7, 'home_score':48, 'favored':'home','spread':27.5,'state':'final'})
        self.transactions.append({'recno':85,'number':5,'away':'BYU', 'home':'Georgia Tech', 'away_score':41, 'home_score':17, 'favored':'home','spread':2.5,'state':'final'})
        self.transactions.append({'recno':86,'number':6,'away':'Southern Cal', 'home':'Arizona', 'away_score':36, 'home_score':39, 'favored':'away','spread':6.5,'state':'final'})
        self.transactions.append({'recno':87,'number':7,'away':'Georgia', 'home':'Florida', 'away_score':17, 'home_score':9, 'favored':'home','spread':6.5,'state':'final'})
        self.transactions.append({'recno':88,'number':8,'away':'Mississippi State', 'home':'Alabama', 'away_score':7, 'home_score':38, 'favored':'home','spread':24.5,'state':'final'})
        self.transactions.append({'recno':89,'number':9,'away':'Notre Dame', 'home':'Oklahoma', 'away_score':30, 'home_score':13, 'favored':'home','spread':10.5,'state':'final'})
        self.transactions.append({'recno':90,'number':10,'away':'Texas Tech', 'home':'Kansas State', 'away_score':24, 'home_score':55, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':91,'number':1,'away':'Virginia Tech', 'home':'Miami-Florida', 'away_score':12, 'home_score':30, 'favored':'away','spread':2.5,'state':'final'})
        self.transactions.append({'recno':92,'number':2,'away':'Texas A&M', 'home':'Mississippi State', 'away_score':38, 'home_score':13, 'favored':'away','spread':7.5,'state':'final'})
        self.transactions.append({'recno':93,'number':3,'away':'TCU', 'home':'West Virginia', 'away_score':39, 'home_score':38, 'favored':'home','spread':6.5,'state':'final'})
        self.transactions.append({'recno':94,'number':4,'away':'Texas', 'home':'Texas Tech', 'away_score':31, 'home_score':22, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':95,'number':5,'away':'Clemson', 'home':'Duke', 'away_score':56, 'home_score':20, 'favored':'away','spread':14.5,'state':'final'})
        self.transactions.append({'recno':96,'number':6,'away':'Nebraska', 'home':'Michigan State', 'away_score':28, 'home_score':24, 'favored':'home','spread':1.5,'state':'final'})
        self.transactions.append({'recno':97,'number':7,'away':'Alabama', 'home':'LSU', 'away_score':21, 'home_score':17, 'favored':'away','spread':10.5,'state':'final'})
        self.transactions.append({'recno':98,'number':8,'away':'Georgia Tech', 'home':'Maryland', 'away_score':33, 'home_score':13, 'favored':'away','spread':7.5,'state':'final'})
        self.transactions.append({'recno':99,'number':9,'away':'Arizona State', 'home':'Oregon State', 'away_score':26, 'home_score':36, 'favored':'home','spread':5.5,'state':'final'})
        self.transactions.append({'recno':100,'number':10,'away':'Oregon', 'home':'Southern Cal', 'away_score':62, 'home_score':51, 'favored':'away','spread':7.5,'state':'final'})
        self.transactions.append({'recno':101,'number':1,'away':'Georgia Tech', 'home':'North Carolina', 'away_score':68, 'home_score':50, 'favored':'home','spread':9.5,'state':'final'})
        self.transactions.append({'recno':102,'number':2,'away':'Mississippi State', 'home':'LSU', 'away_score':17, 'home_score':37, 'favored':'home','spread':13.5,'state':'final'})
        self.transactions.append({'recno':103,'number':3,'away':'Penn State', 'home':'Nebraska', 'away_score':23, 'home_score':32, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':104,'number':4,'away':'West Virginia', 'home':'Oklahoma State', 'away_score':34, 'home_score':55, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':105,'number':5,'away':'Louisville', 'home':'Syracuse', 'away_score':26, 'home_score':45, 'favored':'away','spread':3.5,'state':'final'})
        self.transactions.append({'recno':106,'number':6,'away':'Missouri', 'home':'Tennessee', 'away_score':51, 'home_score':48, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':107,'number':7,'away':'Northwestern', 'home':'Michigan', 'away_score':31, 'home_score':38, 'favored':'home','spread':11.5,'state':'final'})
        self.transactions.append({'recno':108,'number':8,'away':'Arkansas', 'home':'South Carolina', 'away_score':20, 'home_score':38, 'favored':'home','spread':13.5,'state':'final'})
        self.transactions.append({'recno':109,'number':9,'away':'Oregon State', 'home':'Stanford', 'away_score':23, 'home_score':27, 'favored':'home','spread':5.5,'state':'final'})
        self.transactions.append({'recno':110,'number':10,'away':'Texas A&M', 'home':'Alabama', 'away_score':29, 'home_score':24, 'favored':'home','spread':13.5,'state':'final'})
        self.transactions.append({'recno':111,'number':1,'away':'North Carolina', 'home':'Virginia', 'away_score':37, 'home_score':13, 'favored':'away','spread':3.5,'state':'final'})
        self.transactions.append({'recno':112,'number':2,'away':'Temple', 'home':'Army', 'away_score':63, 'home_score':32, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':113,'number':3,'away':'Arkansas', 'home':'Mississippi State', 'away_score':14, 'home_score':45, 'favored':'home','spread':6.5,'state':'final'})
        self.transactions.append({'recno':114,'number':4,'away':'Ohio State', 'home':'Wisconsin', 'away_score':21, 'home_score':14, 'favored':'home','spread':2.5,'state':'final'})
        self.transactions.append({'recno':115,'number':5,'away':'Oklahoma', 'home':'West Virginia', 'away_score':50, 'home_score':49, 'favored':'away','spread':10.5,'state':'final'})
        self.transactions.append({'recno':116,'number':6,'away':'Duke', 'home':'Georgia Tech', 'away_score':24, 'home_score':42, 'favored':'home','spread':13.5,'state':'final'})
        self.transactions.append({'recno':117,'number':7,'away':'Rutgers', 'home':'Cincinnati', 'away_score':10, 'home_score':3, 'favored':'home','spread':6.5,'state':'final'})
        self.transactions.append({'recno':118,'number':8,'away':'NC State', 'home':'Clemson', 'away_score':48, 'home_score':62, 'favored':'home','spread':17.5,'state':'final'})
        self.transactions.append({'recno':119,'number':9,'away':'Tennessee', 'home':'Vanderbilt', 'away_score':18, 'home_score':41, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':120,'number':10,'away':'Southern Cal', 'home':'UCLA', 'away_score':28, 'home_score':38, 'favored':'away','spread':4.5,'state':'final'})
        self.transactions.append({'recno':121,'number':1,'away':'TCU', 'home':'Texas', 'away_score':20, 'home_score':13, 'favored':'home','spread':8.5,'state':'final'})
        self.transactions.append({'recno':122,'number':2,'away':'Stanford', 'home':'UCLA', 'away_score':35, 'home_score':17, 'favored':'away','spread':1.5,'state':'final'})
        self.transactions.append({'recno':123,'number':3,'away':'Michigan', 'home':'Ohio State', 'away_score':21, 'home_score':26, 'favored':'home','spread':4.5,'state':'final'})
        self.transactions.append({'recno':124,'number':4,'away':'Georgia Tech', 'home':'Georgia', 'away_score':10, 'home_score':42, 'favored':'home','spread':13.5,'state':'final'})
        self.transactions.append({'recno':125,'number':5,'away':'Notre Dame', 'home':'Southern Cal', 'away_score':22, 'home_score':13, 'favored':'away','spread':7.5,'state':'final'})
        self.transactions.append({'recno':126,'number':6,'away':'Florida', 'home':'Florida State', 'away_score':37, 'home_score':26, 'favored':'home','spread':0.5,'state':'final'})
        self.transactions.append({'recno':127,'number':7,'away':'Wisconsin', 'home':'Penn State', 'away_score':21, 'home_score':24, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':128,'number':8,'away':'Mississippi State', 'home':'Mississippi', 'away_score':24, 'home_score':41, 'favored':'home','spread':0.5,'state':'final'})
        self.transactions.append({'recno':129,'number':9,'away':'Oregon', 'home':'Oregon State', 'away_score':48, 'home_score':24, 'favored':'away','spread':10.5,'state':'final'})
        self.transactions.append({'recno':130,'number':10,'away':'South Carolina', 'home':'Clemson', 'away_score':27, 'home_score':17, 'favored':'home','spread':4.5,'state':'final'})
        self.transactions.append({'recno':131,'number':1,'away':'North Carolina', 'home':'South Carolina', 'away_score':10, 'home_score':27, 'favored':'home','spread':11.5,'state':'final'})
        self.transactions.append({'recno':132,'number':2,'away':'Utah State', 'home':'Utah', 'away_score':26, 'home_score':30, 'favored':'home','spread':2.5,'state':'final'})
        self.transactions.append({'recno':133,'number':3,'away':'Mississippi State', 'home':'Oklahoma State', 'away_score':3, 'home_score':21, 'favored':'home','spread':12.5,'state':'final'})
        self.transactions.append({'recno':134,'number':4,'away':'Penn State', 'home':'Syracuse', 'away_score':23, 'home_score':17, 'favored':'away','spread':7.5,'state':'final'})
        self.transactions.append({'recno':135,'number':5,'away':'LSU', 'home':'TCU', 'away_score':37, 'home_score':27, 'favored':'away','spread':4.5,'state':'final'})
        self.transactions.append({'recno':136,'number':6,'away':'Boise State', 'home':'Washington', 'away_score':6, 'home_score':38, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':137,'number':7,'away':'Northwestern', 'home':'California', 'away_score':44, 'home_score':30, 'favored':'away','spread':5.5,'state':'final'})
        self.transactions.append({'recno':138,'number':8,'away':'Colorado', 'home':'Colorado State', 'away_score':41, 'home_score':27, 'favored':'home','spread':2.5,'state':'final'})
        self.transactions.append({'recno':139,'number':9,'away':'Florida State', 'home':'Pittsburgh', 'away_score':41, 'home_score':13, 'favored':'away','spread':10.5,'state':'final'})
        self.transactions.append({'recno':140,'number':10,'away':'Georgia', 'home':'Clemson', 'away_score':35, 'home_score':38, 'favored':'away','spread':2.5,'state':'final'})
        self.transactions.append({'recno':141,'number':1,'away':'Wake Forest', 'home':'Boston College', 'away_score':10, 'home_score':24, 'favored':'away','spread':3.5,'state':'final'})
        self.transactions.append({'recno':142,'number':2,'away':'Texas', 'home':'BYU', 'away_score':21, 'home_score':40, 'favored':'away','spread':7.5,'state':'final'})
        self.transactions.append({'recno':143,'number':3,'away':'Florida', 'home':'Miami-Florida', 'away_score':16, 'home_score':21, 'favored':'away','spread':3.5,'state':'final'})
        self.transactions.append({'recno':144,'number':4,'away':'West Virginia', 'home':'Oklahoma', 'away_score':7, 'home_score':16, 'favored':'home','spread':20.5,'state':'final'})
        self.transactions.append({'recno':145,'number':5,'away':'Washington State', 'home':'Southern Cal', 'away_score':10, 'home_score':7, 'favored':'home','spread':14.5,'state':'final'})
        self.transactions.append({'recno':146,'number':6,'away':'Navy', 'home':'Indiana', 'away_score':41, 'home_score':35, 'favored':'home','spread':13.5,'state':'final'})
        self.transactions.append({'recno':147,'number':7,'away':'Cincinnati', 'home':'Illinois', 'away_score':17, 'home_score':45, 'favored':'away','spread':8.5,'state':'final'})
        self.transactions.append({'recno':148,'number':8,'away':'Duke', 'home':'Memphis', 'away_score':28, 'home_score':14, 'favored':'away','spread':6.5,'state':'final'})
        self.transactions.append({'recno':149,'number':9,'away':'Notre Dame', 'home':'Michigan', 'away_score':30, 'home_score':41, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':150,'number':10,'away':'South Carolina', 'home':'Georgia', 'away_score':30, 'home_score':41, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':151,'number':1,'away':'TCU', 'home':'Texas Tech', 'away_score':10, 'home_score':20, 'favored':'away','spread':3.5,'state':'final'})
        self.transactions.append({'recno':152,'number':2,'away':'Louisville', 'home':'Kentucky', 'away_score':27, 'home_score':13, 'favored':'away','spread':12.5,'state':'final'})
        self.transactions.append({'recno':153,'number':3,'away':'UCLA', 'home':'Nebraska', 'away_score':41, 'home_score':21, 'favored':'home','spread':4.5,'state':'final'})
        self.transactions.append({'recno':154,'number':4,'away':'Georgia Tech', 'home':'Duke', 'away_score':38, 'home_score':14, 'favored':'away','spread':8.5,'state':'final'})
        self.transactions.append({'recno':155,'number':5,'away':'Iowa', 'home':'Iowa State', 'away_score':27, 'home_score':21, 'favored':'away','spread':1.5,'state':'final'})
        self.transactions.append({'recno':156,'number':6,'away':'Vanderbilt', 'home':'South Carolina', 'away_score':25, 'home_score':35, 'favored':'home','spread':12.5,'state':'final'})
        self.transactions.append({'recno':157,'number':7,'away':'Mississippi State', 'home':'Auburn', 'away_score':20, 'home_score':24, 'favored':'home','spread':6.5,'state':'final'})
        self.transactions.append({'recno':158,'number':8,'away':'Wisconsin', 'home':'Arizona State', 'away_score':30, 'home_score':32, 'favored':'home','spread':5.5,'state':'final'})
        self.transactions.append({'recno':159,'number':9,'away':'UCF', 'home':'Penn State', 'away_score':34, 'home_score':31, 'favored':'home','spread':5.5,'state':'final'})
        self.transactions.append({'recno':160,'number':10,'away':'Alabama', 'home':'Texas A&M', 'away_score':49, 'home_score':42, 'favored':'away','spread':8.5,'state':'final'})
        self.transactions.append({'recno':161,'number':1,'away':'Clemson', 'home':'NC State', 'away_score':26, 'home_score':14, 'favored':'away','spread':14.5,'state':'final'})
        self.transactions.append({'recno':162,'number':2,'away':'North Carolina', 'home':'Georgia Tech', 'away_score':20, 'home_score':28, 'favored':'home','spread':6.5,'state':'final'})
        self.transactions.append({'recno':163,'number':3,'away':'Michigan State', 'home':'Notre Dame', 'away_score':13, 'home_score':17, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':164,'number':4,'away':'Kansas State', 'home':'Texas', 'away_score':21, 'home_score':31, 'favored':'home','spread':5.5,'state':'final'})
        self.transactions.append({'recno':165,'number':5,'away':'Missouri', 'home':'Indiana', 'away_score':45, 'home_score':28, 'favored':'away','spread':4.5,'state':'final'})
        self.transactions.append({'recno':166,'number':6,'away':'Utah', 'home':'BYU', 'away_score':20, 'home_score':13, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':167,'number':7,'away':'Utah State', 'home':'Southern Cal', 'away_score':14, 'home_score':17, 'favored':'home','spread':6.5,'state':'final'})
        self.transactions.append({'recno':168,'number':8,'away':'Pittsburgh', 'home':'Duke', 'away_score':58, 'home_score':55, 'favored':'away','spread':4.5,'state':'final'})
        self.transactions.append({'recno':169,'number':9,'away':'Tennessee', 'home':'Florida', 'away_score':17, 'home_score':31, 'favored':'home','spread':14.5,'state':'final'})
        self.transactions.append({'recno':170,'number':10,'away':'Arizona State', 'home':'Stanford', 'away_score':28, 'home_score':42, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':171,'number':1,'away':'Virginia Tech', 'home':'Georgia Tech', 'away_score':17, 'home_score':10, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':172,'number':2,'away':'Virginia', 'home':'Pittsburgh', 'away_score':3, 'home_score':14, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':173,'number':3,'away':'Iowa', 'home':'Minnesota', 'away_score':23, 'home_score':7, 'favored':'away','spread':1.5,'state':'final'})
        self.transactions.append({'recno':174,'number':4,'away':'Oklahoma', 'home':'Notre Dame', 'away_score':35, 'home_score':21, 'favored':'away','spread':3.5,'state':'final'})
        self.transactions.append({'recno':175,'number':5,'away':'South Carolina', 'home':'UCF', 'away_score':28, 'home_score':25, 'favored':'away','spread':7.5,'state':'final'})
        self.transactions.append({'recno':176,'number':6,'away':'Arizona', 'home':'Washington', 'away_score':13, 'home_score':31, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':177,'number':7,'away':'LSU', 'home':'Georgia', 'away_score':41, 'home_score':44, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':178,'number':8,'away':'Colorado', 'home':'Oregon State', 'away_score':17, 'home_score':44, 'favored':'home','spread':10.5,'state':'final'})
        self.transactions.append({'recno':179,'number':9,'away':'Mississippi', 'home':'Alabama', 'away_score':0, 'home_score':25, 'favored':'home','spread':16.5,'state':'final'})
        self.transactions.append({'recno':180,'number':10,'away':'Wisconsin', 'home':'Ohio State', 'away_score':24, 'home_score':31, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':181,'number':1,'away':'UCLA', 'home':'Utah', 'away_score':34, 'home_score':27, 'favored':'away','spread':4.5,'state':'final'})
        self.transactions.append({'recno':182,'number':2,'away':'Georgia', 'home':'Tennessee', 'away_score':34, 'home_score':31, 'favored':'away','spread':10.5,'state':'final'})
        self.transactions.append({'recno':183,'number':3,'away':'Clemson', 'home':'Syracuse', 'away_score':49, 'home_score':14, 'favored':'away','spread':13.5,'state':'final'})
        self.transactions.append({'recno':184,'number':4,'away':'Georgia Tech', 'home':'Miami-Florida', 'away_score':30, 'home_score':45, 'favored':'home','spread':4.5,'state':'final'})
        self.transactions.append({'recno':185,'number':5,'away':'North Carolina', 'home':'Virginia Tech', 'away_score':17, 'home_score':27, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':186,'number':6,'away':'Arizona State', 'home':'Notre Dame', 'away_score':34, 'home_score':37, 'favored':'away','spread':5.5,'state':'final'})
        self.transactions.append({'recno':187,'number':7,'away':'Washington', 'home':'Stanford', 'away_score':28, 'home_score':31, 'favored':'home','spread':6.5,'state':'final'})
        self.transactions.append({'recno':188,'number':8,'away':'Mississippi', 'home':'Auburn', 'away_score':22, 'home_score':30, 'favored':'away','spread':3.5,'state':'final'})
        self.transactions.append({'recno':189,'number':9,'away':'Ohio State', 'home':'Northwestern', 'away_score':40, 'home_score':30, 'favored':'away','spread':5.5,'state':'final'})
        self.transactions.append({'recno':190,'number':10,'away':'Maryland', 'home':'Florida State', 'away_score':0, 'home_score':63, 'favored':'home','spread':14.5,'state':'final'})
        self.transactions.append({'recno':191,'number':1,'away':'Rutgers', 'home':'Louisville', 'away_score':10, 'home_score':24, 'favored':'home','spread':17.5,'state':'final'})
        self.transactions.append({'recno':192,'number':2,'away':'Oklahoma', 'home':'Texas', 'away_score':20, 'home_score':36, 'favored':'away','spread':14.5,'state':'final'})
        self.transactions.append({'recno':193,'number':3,'away':'Texas A&M', 'home':'Mississippi', 'away_score':41, 'home_score':38, 'favored':'away','spread':7.5,'state':'final'})
        self.transactions.append({'recno':194,'number':4,'away':'Georgia Tech', 'home':'BYU', 'away_score':20, 'home_score':38, 'favored':'home','spread':6.5,'state':'final'})
        self.transactions.append({'recno':195,'number':5,'away':'Missouri', 'home':'Georgia', 'away_score':41, 'home_score':26, 'favored':'home','spread':9.5,'state':'final'})
        self.transactions.append({'recno':196,'number':6,'away':'Florida', 'home':'LSU', 'away_score':6, 'home_score':17, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':197,'number':7,'away':'Syracuse', 'home':'NC State', 'away_score':24, 'home_score':10, 'favored':'home','spread':5.5,'state':'final'})
        self.transactions.append({'recno':198,'number':8,'away':'South Carolina', 'home':'Arkansas', 'away_score':52, 'home_score':7, 'favored':'away','spread':5.5,'state':'final'})
        self.transactions.append({'recno':199,'number':9,'away':'Michigan', 'home':'Penn State', 'away_score':40, 'home_score':43, 'favored':'away','spread':3.5,'state':'final'})
        self.transactions.append({'recno':200,'number':10,'away':'Oregon', 'home':'Washington', 'away_score':45, 'home_score':24, 'favored':'away','spread':14.5,'state':'final'})
        self.transactions.append({'recno':201,'number':1,'away':'Miami-Florida', 'home':'North Carolina', 'away_score':27, 'home_score':23, 'favored':'away','spread':7.5,'state':'final'})
        self.transactions.append({'recno':202,'number':2,'away':'UCF', 'home':'Louisville', 'away_score':38, 'home_score':35, 'favored':'home','spread':10.5,'state':'final'})
        self.transactions.append({'recno':203,'number':3,'away':'LSU', 'home':'Mississippi', 'away_score':24, 'home_score':27, 'favored':'away','spread':7.5,'state':'final'})
        self.transactions.append({'recno':204,'number':4,'away':'Florida', 'home':'Missouri', 'away_score':17, 'home_score':36, 'favored':'away','spread':3.5,'state':'final'})
        self.transactions.append({'recno':205,'number':5,'away':'Washington', 'home':'Arizona State', 'away_score':24, 'home_score':53, 'favored':'home','spread':3.5,'state':'final'})
        self.transactions.append({'recno':206,'number':6,'away':'TCU', 'home':'Oklahoma State', 'away_score':10, 'home_score':24, 'favored':'home','spread':7.5,'state':'final'})
        self.transactions.append({'recno':207,'number':7,'away':'UCLA', 'home':'Stanford', 'away_score':10, 'home_score':24, 'favored':'home','spread':5.5,'state':'final'})
        self.transactions.append({'recno':208,'number':8,'away':'Auburn', 'home':'Texas A&M', 'away_score':45, 'home_score':41, 'favored':'home','spread':13.5,'state':'final'})
        self.transactions.append({'recno':209,'number':9,'away':'South Carolina', 'home':'Tennessee', 'away_score':21, 'home_score':23, 'favored':'away','spread':7.5,'state':'final'})
        self.transactions.append({'recno':210,'number':10,'away':'Florida State', 'home':'Clemson', 'away_score':51, 'home_score':14, 'favored':'away','spread':3.5,'state':'final'})
        self.transactions.append({'recno':211,'number':1,'away':'Kentucky', 'home':'Mississippi State', 'away_score':None, 'home_score':None, 'favored':'home','spread':10.5,'state':'not_started'})
        self.transactions.append({'recno':212,'number':2,'away':'Northwestern', 'home':'Iowa', 'away_score':None, 'home_score':None, 'favored':'home','spread':4.5,'state':'not_started'})
        self.transactions.append({'recno':213,'number':3,'away':'Georgia Tech', 'home':'Virginia', 'away_score':None, 'home_score':None, 'favored':'away','spread':9.5,'state':'not_started'})
        self.transactions.append({'recno':214,'number':4,'away':'Clemson', 'home':'Maryland', 'away_score':None, 'home_score':None, 'favored':'away','spread':13.5,'state':'not_started'})
        self.transactions.append({'recno':215,'number':5,'away':'UCLA', 'home':'Oregon', 'away_score':None, 'home_score':None, 'favored':'home','spread':22.5,'state':'not_started'})
        self.transactions.append({'recno':216,'number':6,'away':'Stanford', 'home':'Oregon State', 'away_score':None, 'home_score':None, 'favored':'away','spread':5.5,'state':'not_started'})
        self.transactions.append({'recno':217,'number':7,'away':'Texas', 'home':'TCU', 'away_score':None, 'home_score':None, 'favored':'home','spread':1.5,'state':'not_started'})
        self.transactions.append({'recno':218,'number':8,'away':'South Carolina', 'home':'Missouri', 'away_score':None, 'home_score':None, 'favored':'home','spread':5.5,'state':'not_started'})
        self.transactions.append({'recno':219,'number':9,'away':'Penn State', 'home':'Ohio State', 'away_score':None, 'home_score':None, 'favored':'home','spread':14.5,'state':'not_started'})
        self.transactions.append({'recno':220,'number':10,'away':'Texas Tech', 'home':'Oklahoma', 'away_score':None, 'home_score':None, 'favored':'home','spread':7.5,'state':'not_started'})

