from models.games import *
from models.teams import *
from lookups import *
from google.appengine.ext import db

class LoadGames:

    def __init__(self):
        self.load()

    def num_transactions(self):
        return len(self.transactions)

    def run_transactions(self,txn_range):
        last_index = self.num_transactions() - 1
        for i in txn_range:
            if i > last_index:
                break
            d = self.transactions[i]
            self.add_game(d)

    def __lookup_team(self,team):
        q = db.GqlQuery('SELECT * FROM Team WHERE name=:name',name=team)
        assert q
        result = list(q)
        assert len(result) == 1
        return str(q[0].key())

    def add_game(self,game):
        g = Game()
        g.number = game['number']
        g.team1 = self.__lookup_team(game['team1'])
        g.team2 = self.__lookup_team(game['team2'])
        g.team1_score = game['team1_score']
        g.team2_score = game['team2_score']
        g.favored = game['favored']
        g.spread = game['spread']
        g.state = game['state']
        g.quarter = ''
        g.time_left = ''
        g.date = None
        key = g.put()
        l = Lookup(name='game',recno=game['recno'],instance_key=str(key))
        l.put()

    def load(self):
        self.transactions = []
        self.transactions.append({'recno':1,'number':1,'team1':'South Carolina', 'team2':'Vanderbilt', 'team1_score':17, 'team2_score':13, 'favored':'team1','spread':7.5,'state':'final'})
        self.transactions.append({'recno':2,'number':2,'team1':'Northwestern', 'team2':'Syracuse', 'team1_score':42, 'team2_score':41, 'favored':'team1','spread':1.5,'state':'final'})
        self.transactions.append({'recno':3,'number':3,'team1':'Tennessee', 'team2':'NC State', 'team1_score':35, 'team2_score':21, 'favored':'team1','spread':3.5,'state':'final'})
        self.transactions.append({'recno':4,'number':4,'team1':'Boise State', 'team2':'Michigan State', 'team1_score':13, 'team2_score':17, 'favored':'team2','spread':6.5,'state':'final'})
        self.transactions.append({'recno':5,'number':5,'team1':'Miami-Florida', 'team2':'Boston College', 'team1_score':41, 'team2_score':32, 'favored':'team1','spread':0.5,'state':'final'})
        self.transactions.append({'recno':6,'number':6,'team1':'Colorado State', 'team2':'Colorado', 'team1_score':22, 'team2_score':17, 'favored':'team2','spread':6.5,'state':'final'})
        self.transactions.append({'recno':7,'number':7,'team1':'Kentucky', 'team2':'Louisville', 'team1_score':14, 'team2_score':32, 'favored':'team2','spread':13.5,'state':'final'})
        self.transactions.append({'recno':8,'number':8,'team1':'Georgia Tech', 'team2':'Virginia Tech', 'team1_score':17, 'team2_score':20, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':9,'number':9,'team1':'Michigan', 'team2':'Alabama', 'team1_score':14, 'team2_score':41, 'favored':'team2','spread':13.5,'state':'final'})
        self.transactions.append({'recno':10,'number':10,'team1':'Clemson', 'team2':'Auburn', 'team1_score':26, 'team2_score':19, 'favored':'team1','spread':3.5,'state':'final'})
        self.transactions.append({'recno':11,'number':1,'team1':'Penn State', 'team2':'Virginia', 'team1_score':16, 'team2_score':17, 'favored':'team2','spread':10.5,'state':'final'})
        self.transactions.append({'recno':12,'number':2,'team1':'Miami-Florida', 'team2':'Kansas State', 'team1_score':13, 'team2_score':52, 'favored':'team2','spread':6.5,'state':'final'})
        self.transactions.append({'recno':13,'number':3,'team1':'Auburn', 'team2':'Mississippi State', 'team1_score':10, 'team2_score':28, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':14,'number':4,'team1':'North Carolina', 'team2':'Wake Forest', 'team1_score':27, 'team2_score':28, 'favored':'team1','spread':8.5,'state':'final'})
        self.transactions.append({'recno':15,'number':5,'team1':'Florida', 'team2':'Texas A&M', 'team1_score':20, 'team2_score':17, 'favored':'team2','spread':1.5,'state':'final'})
        self.transactions.append({'recno':16,'number':6,'team1':'Iowa State', 'team2':'Iowa', 'team1_score':9, 'team2_score':6, 'favored':'team2','spread':4.5,'state':'final'})
        self.transactions.append({'recno':17,'number':7,'team1':'Wisconsin', 'team2':'Oregon State', 'team1_score':7, 'team2_score':10, 'favored':'team1','spread':8.5,'state':'final'})
        self.transactions.append({'recno':18,'number':8,'team1':'Nebraska', 'team2':'UCLA', 'team1_score':30, 'team2_score':36, 'favored':'team1','spread':5.5,'state':'final'})
        self.transactions.append({'recno':19,'number':9,'team1':'Illinois', 'team2':'Arizona State', 'team1_score':14, 'team2_score':45, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':20,'number':10,'team1':'Georgia', 'team2':'Missouri', 'team1_score':41, 'team2_score':20, 'favored':'team1','spread':3.5,'state':'final'})
        self.transactions.append({'recno':21,'number':1,'team1':'Rutgers', 'team2':'South Florida', 'team1_score':23, 'team2_score':13, 'favored':'team2','spread':9.5,'state':'final'})
        self.transactions.append({'recno':22,'number':2,'team1':'California', 'team2':'Ohio State', 'team1_score':28, 'team2_score':35, 'favored':'team2','spread':17.5,'state':'final'})
        self.transactions.append({'recno':23,'number':3,'team1':'Texas', 'team2':'Mississippi', 'team1_score':66, 'team2_score':31, 'favored':'team1','spread':10.5,'state':'final'})
        self.transactions.append({'recno':24,'number':4,'team1':'North Carolina', 'team2':'Louisville', 'team1_score':34, 'team2_score':39, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':25,'number':5,'team1':'Virginia', 'team2':'Georgia Tech', 'team1_score':20, 'team2_score':56, 'favored':'team2','spread':10.5,'state':'final'})
        self.transactions.append({'recno':26,'number':6,'team1':'Florida', 'team2':'Tennessee', 'team1_score':37, 'team2_score':20, 'favored':'team2','spread':2.5,'state':'final'})
        self.transactions.append({'recno':27,'number':7,'team1':'Arizona State', 'team2':'Missouri', 'team1_score':20, 'team2_score':24, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':28,'number':8,'team1':'Southern Cal', 'team2':'Stanford', 'team1_score':14, 'team2_score':21, 'favored':'team1','spread':10.5,'state':'final'})
        self.transactions.append({'recno':29,'number':9,'team1':'Virginia Tech', 'team2':'Pittsburgh', 'team1_score':17, 'team2_score':35, 'favored':'team1','spread':12.5,'state':'final'})
        self.transactions.append({'recno':30,'number':10,'team1':'Notre Dame', 'team2':'Michigan State', 'team1_score':20, 'team2_score':3, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':31,'number':1,'team1':'BYU', 'team2':'Boise State', 'team1_score':6, 'team2_score':7, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':32,'number':2,'team1':'Miami-Florida', 'team2':'Georgia Tech', 'team1_score':42, 'team2_score':36, 'favored':'team2','spread':13.5,'state':'final'})
        self.transactions.append({'recno':33,'number':3,'team1':'Michigan', 'team2':'Notre Dame', 'team1_score':6, 'team2_score':13, 'favored':'team2','spread':6.5,'state':'final'})
        self.transactions.append({'recno':34,'number':4,'team1':'Rutgers', 'team2':'Arkansas', 'team1_score':35, 'team2_score':26, 'favored':'team2','spread':5.5,'state':'final'})
        self.transactions.append({'recno':35,'number':5,'team1':'Kansas State', 'team2':'Oklahoma', 'team1_score':24, 'team2_score':19, 'favored':'team2','spread':13.5,'state':'final'})
        self.transactions.append({'recno':36,'number':6,'team1':'Missouri', 'team2':'South Carolina', 'team1_score':10, 'team2_score':31, 'favored':'team2','spread':9.5,'state':'final'})
        self.transactions.append({'recno':37,'number':7,'team1':'Utah', 'team2':'Arizona State', 'team1_score':7, 'team2_score':37, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':38,'number':8,'team1':'Baylor', 'team2':'Louisiana Monroe', 'team1_score':47, 'team2_score':42, 'favored':'team1','spread':7.5,'state':'final'})
        self.transactions.append({'recno':39,'number':9,'team1':'Oregon State', 'team2':'UCLA', 'team1_score':27, 'team2_score':20, 'favored':'team2','spread':11.5,'state':'final'})
        self.transactions.append({'recno':40,'number':10,'team1':'Clemson', 'team2':'Florida State', 'team1_score':37, 'team2_score':49, 'favored':'team2','spread':13.5,'state':'final'})
        self.transactions.append({'recno':41,'number':1,'team1':'Stanford', 'team2':'Washington', 'team1_score':13, 'team2_score':17, 'favored':'team1','spread':7.5,'state':'final'})
        self.transactions.append({'recno':42,'number':2,'team1':'Tennessee', 'team2':'Georgia', 'team1_score':44, 'team2_score':51, 'favored':'team2','spread':14.5,'state':'final'})
        self.transactions.append({'recno':43,'number':3,'team1':'Baylor', 'team2':'West Virginia', 'team1_score':63, 'team2_score':70, 'favored':'team2','spread':13.5,'state':'final'})
        self.transactions.append({'recno':44,'number':4,'team1':'Ohio State', 'team2':'Michigan State', 'team1_score':17, 'team2_score':16, 'favored':'team2','spread':2.5,'state':'final'})
        self.transactions.append({'recno':45,'number':5,'team1':'NC State', 'team2':'Miami-Florida', 'team1_score':37, 'team2_score':44, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':46,'number':6,'team1':'Arkansas', 'team2':'Texas A&M', 'team1_score':10, 'team2_score':58, 'favored':'team2','spread':13.5,'state':'final'})
        self.transactions.append({'recno':47,'number':7,'team1':'Oregon State', 'team2':'Arizona', 'team1_score':38, 'team2_score':35, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':48,'number':8,'team1':'Clemson', 'team2':'Boston College', 'team1_score':45, 'team2_score':31, 'favored':'team1','spread':9.5,'state':'final'})
        self.transactions.append({'recno':49,'number':9,'team1':'Duke', 'team2':'Wake Forest', 'team1_score':34, 'team2_score':27, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':50,'number':10,'team1':'Texas', 'team2':'Oklahoma State', 'team1_score':41, 'team2_score':36, 'favored':'team1','spread':2.5,'state':'final'})
        self.transactions.append({'recno':51,'number':1,'team1':'Pittsburgh', 'team2':'Syracuse', 'team1_score':13, 'team2_score':14, 'favored':'team1','spread':2.5,'state':'final'})
        self.transactions.append({'recno':52,'number':2,'team1':'Virginia Tech', 'team2':'North Carolina', 'team1_score':34, 'team2_score':48, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':53,'number':3,'team1':'UCLA', 'team2':'California', 'team1_score':17, 'team2_score':43, 'favored':'team1','spread':2.5,'state':'final'})
        self.transactions.append({'recno':54,'number':4,'team1':'LSU', 'team2':'Florida', 'team1_score':6, 'team2_score':14, 'favored':'team1','spread':2.5,'state':'final'})
        self.transactions.append({'recno':55,'number':5,'team1':'Georgia Tech', 'team2':'Clemson', 'team1_score':31, 'team2_score':47, 'favored':'team2','spread':9.5,'state':'final'})
        self.transactions.append({'recno':56,'number':6,'team1':'Oklahoma', 'team2':'Texas Tech', 'team1_score':41, 'team2_score':20, 'favored':'team1','spread':3.5,'state':'final'})
        self.transactions.append({'recno':57,'number':7,'team1':'Michigan', 'team2':'Purdue', 'team1_score':44, 'team2_score':13, 'favored':'team1','spread':3.5,'state':'final'})
        self.transactions.append({'recno':58,'number':8,'team1':'West Virginia', 'team2':'Texas', 'team1_score':48, 'team2_score':45, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':59,'number':9,'team1':'Nebraska', 'team2':'Ohio State', 'team1_score':38, 'team2_score':63, 'favored':'team2','spread':4.5,'state':'final'})
        self.transactions.append({'recno':60,'number':10,'team1':'Georgia', 'team2':'South Carolina', 'team1_score':7, 'team2_score':35, 'favored':'team2','spread':2.5,'state':'final'})
        self.transactions.append({'recno':61,'number':1,'team1':'Oregon State', 'team2':'BYU', 'team1_score':42, 'team2_score':24, 'favored':'team2','spread':2.5,'state':'final'})
        self.transactions.append({'recno':62,'number':2,'team1':'West Virginia', 'team2':'Texas Tech', 'team1_score':14, 'team2_score':49, 'favored':'team1','spread':4.5,'state':'final'})
        self.transactions.append({'recno':63,'number':3,'team1':'Florida', 'team2':'Vanderbilt', 'team1_score':31, 'team2_score':17, 'favored':'team1','spread':7.5,'state':'final'})
        self.transactions.append({'recno':64,'number':4,'team1':'South Carolina', 'team2':'LSU', 'team1_score':21, 'team2_score':23, 'favored':'team2','spread':2.5,'state':'final'})
        self.transactions.append({'recno':65,'number':5,'team1':'Tennessee', 'team2':'Mississippi State', 'team1_score':31, 'team2_score':41, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':66,'number':6,'team1':'Texas A&M', 'team2':'Louisiana Tech', 'team1_score':59, 'team2_score':57, 'favored':'team1','spread':7.5,'state':'final'})
        self.transactions.append({'recno':67,'number':7,'team1':'Maryland', 'team2':'Virginia', 'team1_score':27, 'team2_score':20, 'favored':'team2','spread':2.5,'state':'final'})
        self.transactions.append({'recno':68,'number':8,'team1':'Stanford', 'team2':'Notre Dame', 'team1_score':13, 'team2_score':20, 'favored':'team2','spread':9.5,'state':'final'})
        self.transactions.append({'recno':69,'number':9,'team1':'Wisconsin', 'team2':'Purdue', 'team1_score':38, 'team2_score':14, 'favored':'team2','spread':0.5,'state':'final'})
        self.transactions.append({'recno':70,'number':10,'team1':'Texas', 'team2':'Oklahoma', 'team1_score':21, 'team2_score':63, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':71,'number':1,'team1':'Oregon', 'team2':'Arizona State', 'team1_score':43, 'team2_score':21, 'favored':'team1','spread':9.5,'state':'final'})
        self.transactions.append({'recno':72,'number':2,'team1':'Nebraska', 'team2':'Northwestern', 'team1_score':29, 'team2_score':28, 'favored':'team1','spread':4.5,'state':'final'})
        self.transactions.append({'recno':73,'number':3,'team1':'Florida State', 'team2':'Miami-Florida', 'team1_score':33, 'team2_score':20, 'favored':'team1','spread':12.5,'state':'final'})
        self.transactions.append({'recno':74,'number':4,'team1':'Virginia Tech', 'team2':'Clemson', 'team1_score':17, 'team2_score':38, 'favored':'team2','spread':8.5,'state':'final'})
        self.transactions.append({'recno':75,'number':5,'team1':'Michigan State', 'team2':'Michigan', 'team1_score':10, 'team2_score':12, 'favored':'team2','spread':10.5,'state':'final'})
        self.transactions.append({'recno':76,'number':6,'team1':'Penn State', 'team2':'Iowa', 'team1_score':38, 'team2_score':14, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':77,'number':7,'team1':'LSU', 'team2':'Texas A&M', 'team1_score':24, 'team2_score':19, 'favored':'team1','spread':3.5,'state':'final'})
        self.transactions.append({'recno':78,'number':8,'team1':'Kansas State', 'team2':'West Virginia', 'team1_score':55, 'team2_score':14, 'favored':'team2','spread':2.5,'state':'final'})
        self.transactions.append({'recno':79,'number':9,'team1':'Texas Tech', 'team2':'TCU', 'team1_score':56, 'team2_score':53, 'favored':'team1','spread':2.5,'state':'final'})
        self.transactions.append({'recno':80,'number':10,'team1':'South Carolina', 'team2':'Florida', 'team1_score':11, 'team2_score':44, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':81,'number':1,'team1':'Clemson', 'team2':'Wake Forest', 'team1_score':42, 'team2_score':13, 'favored':'team1','spread':12.5,'state':'final'})
        self.transactions.append({'recno':82,'number':2,'team1':'Cincinnati', 'team2':'Louisville', 'team1_score':31, 'team2_score':34, 'favored':'team2','spread':4.5,'state':'final'})
        self.transactions.append({'recno':83,'number':3,'team1':'Tennessee', 'team2':'South Carolina', 'team1_score':35, 'team2_score':38, 'favored':'team2','spread':14.5,'state':'final'})
        self.transactions.append({'recno':84,'number':4,'team1':'Duke', 'team2':'Florida State', 'team1_score':7, 'team2_score':48, 'favored':'team2','spread':27.5,'state':'final'})
        self.transactions.append({'recno':85,'number':5,'team1':'BYU', 'team2':'Georgia Tech', 'team1_score':41, 'team2_score':17, 'favored':'team2','spread':2.5,'state':'final'})
        self.transactions.append({'recno':86,'number':6,'team1':'Southern Cal', 'team2':'Arizona', 'team1_score':36, 'team2_score':39, 'favored':'team1','spread':6.5,'state':'final'})
        self.transactions.append({'recno':87,'number':7,'team1':'Georgia', 'team2':'Florida', 'team1_score':17, 'team2_score':9, 'favored':'team2','spread':6.5,'state':'final'})
        self.transactions.append({'recno':88,'number':8,'team1':'Mississippi State', 'team2':'Alabama', 'team1_score':7, 'team2_score':38, 'favored':'team2','spread':24.5,'state':'final'})
        self.transactions.append({'recno':89,'number':9,'team1':'Notre Dame', 'team2':'Oklahoma', 'team1_score':30, 'team2_score':13, 'favored':'team2','spread':10.5,'state':'final'})
        self.transactions.append({'recno':90,'number':10,'team1':'Texas Tech', 'team2':'Kansas State', 'team1_score':24, 'team2_score':55, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':91,'number':1,'team1':'Virginia Tech', 'team2':'Miami-Florida', 'team1_score':12, 'team2_score':30, 'favored':'team1','spread':2.5,'state':'final'})
        self.transactions.append({'recno':92,'number':2,'team1':'Texas A&M', 'team2':'Mississippi State', 'team1_score':38, 'team2_score':13, 'favored':'team1','spread':7.5,'state':'final'})
        self.transactions.append({'recno':93,'number':3,'team1':'TCU', 'team2':'West Virginia', 'team1_score':39, 'team2_score':38, 'favored':'team2','spread':6.5,'state':'final'})
        self.transactions.append({'recno':94,'number':4,'team1':'Texas', 'team2':'Texas Tech', 'team1_score':31, 'team2_score':22, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':95,'number':5,'team1':'Clemson', 'team2':'Duke', 'team1_score':56, 'team2_score':20, 'favored':'team1','spread':14.5,'state':'final'})
        self.transactions.append({'recno':96,'number':6,'team1':'Nebraska', 'team2':'Michigan State', 'team1_score':28, 'team2_score':24, 'favored':'team2','spread':1.5,'state':'final'})
        self.transactions.append({'recno':97,'number':7,'team1':'Alabama', 'team2':'LSU', 'team1_score':21, 'team2_score':17, 'favored':'team1','spread':10.5,'state':'final'})
        self.transactions.append({'recno':98,'number':8,'team1':'Georgia Tech', 'team2':'Maryland', 'team1_score':33, 'team2_score':13, 'favored':'team1','spread':7.5,'state':'final'})
        self.transactions.append({'recno':99,'number':9,'team1':'Arizona State', 'team2':'Oregon State', 'team1_score':26, 'team2_score':36, 'favored':'team2','spread':5.5,'state':'final'})
        self.transactions.append({'recno':100,'number':10,'team1':'Oregon', 'team2':'Southern Cal', 'team1_score':62, 'team2_score':51, 'favored':'team1','spread':7.5,'state':'final'})
        self.transactions.append({'recno':101,'number':1,'team1':'Georgia Tech', 'team2':'North Carolina', 'team1_score':68, 'team2_score':50, 'favored':'team2','spread':9.5,'state':'final'})
        self.transactions.append({'recno':102,'number':2,'team1':'Mississippi State', 'team2':'LSU', 'team1_score':17, 'team2_score':37, 'favored':'team2','spread':13.5,'state':'final'})
        self.transactions.append({'recno':103,'number':3,'team1':'Penn State', 'team2':'Nebraska', 'team1_score':23, 'team2_score':32, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':104,'number':4,'team1':'West Virginia', 'team2':'Oklahoma State', 'team1_score':34, 'team2_score':55, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':105,'number':5,'team1':'Louisville', 'team2':'Syracuse', 'team1_score':26, 'team2_score':45, 'favored':'team1','spread':3.5,'state':'final'})
        self.transactions.append({'recno':106,'number':6,'team1':'Missouri', 'team2':'Tennessee', 'team1_score':51, 'team2_score':48, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':107,'number':7,'team1':'Northwestern', 'team2':'Michigan', 'team1_score':31, 'team2_score':38, 'favored':'team2','spread':11.5,'state':'final'})
        self.transactions.append({'recno':108,'number':8,'team1':'Arkansas', 'team2':'South Carolina', 'team1_score':20, 'team2_score':38, 'favored':'team2','spread':13.5,'state':'final'})
        self.transactions.append({'recno':109,'number':9,'team1':'Oregon State', 'team2':'Stanford', 'team1_score':23, 'team2_score':27, 'favored':'team2','spread':5.5,'state':'final'})
        self.transactions.append({'recno':110,'number':10,'team1':'Texas A&M', 'team2':'Alabama', 'team1_score':29, 'team2_score':24, 'favored':'team2','spread':13.5,'state':'final'})
        self.transactions.append({'recno':111,'number':1,'team1':'North Carolina', 'team2':'Virginia', 'team1_score':37, 'team2_score':13, 'favored':'team1','spread':3.5,'state':'final'})
        self.transactions.append({'recno':112,'number':2,'team1':'Temple', 'team2':'Army', 'team1_score':63, 'team2_score':32, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':113,'number':3,'team1':'Arkansas', 'team2':'Mississippi State', 'team1_score':14, 'team2_score':45, 'favored':'team2','spread':6.5,'state':'final'})
        self.transactions.append({'recno':114,'number':4,'team1':'Ohio State', 'team2':'Wisconsin', 'team1_score':21, 'team2_score':14, 'favored':'team2','spread':2.5,'state':'final'})
        self.transactions.append({'recno':115,'number':5,'team1':'Oklahoma', 'team2':'West Virginia', 'team1_score':50, 'team2_score':49, 'favored':'team1','spread':10.5,'state':'final'})
        self.transactions.append({'recno':116,'number':6,'team1':'Duke', 'team2':'Georgia Tech', 'team1_score':24, 'team2_score':42, 'favored':'team2','spread':13.5,'state':'final'})
        self.transactions.append({'recno':117,'number':7,'team1':'Rutgers', 'team2':'Cincinnati', 'team1_score':10, 'team2_score':3, 'favored':'team2','spread':6.5,'state':'final'})
        self.transactions.append({'recno':118,'number':8,'team1':'NC State', 'team2':'Clemson', 'team1_score':48, 'team2_score':62, 'favored':'team2','spread':17.5,'state':'final'})
        self.transactions.append({'recno':119,'number':9,'team1':'Tennessee', 'team2':'Vanderbilt', 'team1_score':18, 'team2_score':41, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':120,'number':10,'team1':'Southern Cal', 'team2':'UCLA', 'team1_score':28, 'team2_score':38, 'favored':'team1','spread':4.5,'state':'final'})
        self.transactions.append({'recno':121,'number':1,'team1':'TCU', 'team2':'Texas', 'team1_score':20, 'team2_score':13, 'favored':'team2','spread':8.5,'state':'final'})
        self.transactions.append({'recno':122,'number':2,'team1':'Stanford', 'team2':'UCLA', 'team1_score':35, 'team2_score':17, 'favored':'team1','spread':1.5,'state':'final'})
        self.transactions.append({'recno':123,'number':3,'team1':'Michigan', 'team2':'Ohio State', 'team1_score':21, 'team2_score':26, 'favored':'team2','spread':4.5,'state':'final'})
        self.transactions.append({'recno':124,'number':4,'team1':'Georgia Tech', 'team2':'Georgia', 'team1_score':10, 'team2_score':42, 'favored':'team2','spread':13.5,'state':'final'})
        self.transactions.append({'recno':125,'number':5,'team1':'Notre Dame', 'team2':'Southern Cal', 'team1_score':22, 'team2_score':13, 'favored':'team1','spread':7.5,'state':'final'})
        self.transactions.append({'recno':126,'number':6,'team1':'Florida', 'team2':'Florida State', 'team1_score':37, 'team2_score':26, 'favored':'team2','spread':0.5,'state':'final'})
        self.transactions.append({'recno':127,'number':7,'team1':'Wisconsin', 'team2':'Penn State', 'team1_score':21, 'team2_score':24, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':128,'number':8,'team1':'Mississippi State', 'team2':'Mississippi', 'team1_score':24, 'team2_score':41, 'favored':'team2','spread':0.5,'state':'final'})
        self.transactions.append({'recno':129,'number':9,'team1':'Oregon', 'team2':'Oregon State', 'team1_score':48, 'team2_score':24, 'favored':'team1','spread':10.5,'state':'final'})
        self.transactions.append({'recno':130,'number':10,'team1':'South Carolina', 'team2':'Clemson', 'team1_score':27, 'team2_score':17, 'favored':'team2','spread':4.5,'state':'final'})
        self.transactions.append({'recno':131,'number':1,'team1':'North Carolina', 'team2':'South Carolina', 'team1_score':10, 'team2_score':27, 'favored':'team2','spread':11.5,'state':'final'})
        self.transactions.append({'recno':132,'number':2,'team1':'Utah State', 'team2':'Utah', 'team1_score':26, 'team2_score':30, 'favored':'team2','spread':2.5,'state':'final'})
        self.transactions.append({'recno':133,'number':3,'team1':'Mississippi State', 'team2':'Oklahoma State', 'team1_score':3, 'team2_score':21, 'favored':'team2','spread':12.5,'state':'final'})
        self.transactions.append({'recno':134,'number':4,'team1':'Penn State', 'team2':'Syracuse', 'team1_score':23, 'team2_score':17, 'favored':'team1','spread':7.5,'state':'final'})
        self.transactions.append({'recno':135,'number':5,'team1':'LSU', 'team2':'TCU', 'team1_score':37, 'team2_score':27, 'favored':'team1','spread':4.5,'state':'final'})
        self.transactions.append({'recno':136,'number':6,'team1':'Boise State', 'team2':'Washington', 'team1_score':6, 'team2_score':38, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':137,'number':7,'team1':'Northwestern', 'team2':'California', 'team1_score':44, 'team2_score':30, 'favored':'team1','spread':5.5,'state':'final'})
        self.transactions.append({'recno':138,'number':8,'team1':'Colorado', 'team2':'Colorado State', 'team1_score':41, 'team2_score':27, 'favored':'team2','spread':2.5,'state':'final'})
        self.transactions.append({'recno':139,'number':9,'team1':'Florida State', 'team2':'Pittsburgh', 'team1_score':41, 'team2_score':13, 'favored':'team1','spread':10.5,'state':'final'})
        self.transactions.append({'recno':140,'number':10,'team1':'Georgia', 'team2':'Clemson', 'team1_score':35, 'team2_score':38, 'favored':'team1','spread':2.5,'state':'final'})
        self.transactions.append({'recno':141,'number':1,'team1':'Wake Forest', 'team2':'Boston College', 'team1_score':10, 'team2_score':24, 'favored':'team1','spread':3.5,'state':'final'})
        self.transactions.append({'recno':142,'number':2,'team1':'Texas', 'team2':'BYU', 'team1_score':21, 'team2_score':40, 'favored':'team1','spread':7.5,'state':'final'})
        self.transactions.append({'recno':143,'number':3,'team1':'Florida', 'team2':'Miami-Florida', 'team1_score':16, 'team2_score':21, 'favored':'team1','spread':3.5,'state':'final'})
        self.transactions.append({'recno':144,'number':4,'team1':'West Virginia', 'team2':'Oklahoma', 'team1_score':7, 'team2_score':16, 'favored':'team2','spread':20.5,'state':'final'})
        self.transactions.append({'recno':145,'number':5,'team1':'Washington State', 'team2':'Southern Cal', 'team1_score':10, 'team2_score':7, 'favored':'team2','spread':14.5,'state':'final'})
        self.transactions.append({'recno':146,'number':6,'team1':'Navy', 'team2':'Indiana', 'team1_score':41, 'team2_score':35, 'favored':'team2','spread':13.5,'state':'final'})
        self.transactions.append({'recno':147,'number':7,'team1':'Cincinnati', 'team2':'Illinois', 'team1_score':17, 'team2_score':45, 'favored':'team1','spread':8.5,'state':'final'})
        self.transactions.append({'recno':148,'number':8,'team1':'Duke', 'team2':'Memphis', 'team1_score':28, 'team2_score':14, 'favored':'team1','spread':6.5,'state':'final'})
        self.transactions.append({'recno':149,'number':9,'team1':'Notre Dame', 'team2':'Michigan', 'team1_score':30, 'team2_score':41, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':150,'number':10,'team1':'South Carolina', 'team2':'Georgia', 'team1_score':30, 'team2_score':41, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':151,'number':1,'team1':'TCU', 'team2':'Texas Tech', 'team1_score':10, 'team2_score':20, 'favored':'team1','spread':3.5,'state':'final'})
        self.transactions.append({'recno':152,'number':2,'team1':'Louisville', 'team2':'Kentucky', 'team1_score':27, 'team2_score':13, 'favored':'team1','spread':12.5,'state':'final'})
        self.transactions.append({'recno':153,'number':3,'team1':'UCLA', 'team2':'Nebraska', 'team1_score':41, 'team2_score':21, 'favored':'team2','spread':4.5,'state':'final'})
        self.transactions.append({'recno':154,'number':4,'team1':'Georgia Tech', 'team2':'Duke', 'team1_score':38, 'team2_score':14, 'favored':'team1','spread':8.5,'state':'final'})
        self.transactions.append({'recno':155,'number':5,'team1':'Iowa', 'team2':'Iowa State', 'team1_score':27, 'team2_score':21, 'favored':'team1','spread':1.5,'state':'final'})
        self.transactions.append({'recno':156,'number':6,'team1':'Vanderbilt', 'team2':'South Carolina', 'team1_score':25, 'team2_score':35, 'favored':'team2','spread':12.5,'state':'final'})
        self.transactions.append({'recno':157,'number':7,'team1':'Mississippi State', 'team2':'Auburn', 'team1_score':20, 'team2_score':24, 'favored':'team2','spread':6.5,'state':'final'})
        self.transactions.append({'recno':158,'number':8,'team1':'Wisconsin', 'team2':'Arizona State', 'team1_score':30, 'team2_score':32, 'favored':'team2','spread':5.5,'state':'final'})
        self.transactions.append({'recno':159,'number':9,'team1':'UCF', 'team2':'Penn State', 'team1_score':34, 'team2_score':31, 'favored':'team2','spread':5.5,'state':'final'})
        self.transactions.append({'recno':160,'number':10,'team1':'Alabama', 'team2':'Texas A&M', 'team1_score':49, 'team2_score':42, 'favored':'team1','spread':8.5,'state':'final'})
        self.transactions.append({'recno':161,'number':1,'team1':'Clemson', 'team2':'NC State', 'team1_score':26, 'team2_score':14, 'favored':'team1','spread':14.5,'state':'final'})
        self.transactions.append({'recno':162,'number':2,'team1':'North Carolina', 'team2':'Georgia Tech', 'team1_score':20, 'team2_score':28, 'favored':'team2','spread':6.5,'state':'final'})
        self.transactions.append({'recno':163,'number':3,'team1':'Michigan State', 'team2':'Notre Dame', 'team1_score':13, 'team2_score':17, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':164,'number':4,'team1':'Kansas State', 'team2':'Texas', 'team1_score':21, 'team2_score':31, 'favored':'team2','spread':5.5,'state':'final'})
        self.transactions.append({'recno':165,'number':5,'team1':'Missouri', 'team2':'Indiana', 'team1_score':45, 'team2_score':28, 'favored':'team1','spread':4.5,'state':'final'})
        self.transactions.append({'recno':166,'number':6,'team1':'Utah', 'team2':'BYU', 'team1_score':20, 'team2_score':13, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':167,'number':7,'team1':'Utah State', 'team2':'Southern Cal', 'team1_score':14, 'team2_score':17, 'favored':'team2','spread':6.5,'state':'final'})
        self.transactions.append({'recno':168,'number':8,'team1':'Pittsburgh', 'team2':'Duke', 'team1_score':58, 'team2_score':55, 'favored':'team1','spread':4.5,'state':'final'})
        self.transactions.append({'recno':169,'number':9,'team1':'Tennessee', 'team2':'Florida', 'team1_score':17, 'team2_score':31, 'favored':'team2','spread':14.5,'state':'final'})
        self.transactions.append({'recno':170,'number':10,'team1':'Arizona State', 'team2':'Stanford', 'team1_score':28, 'team2_score':42, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':171,'number':1,'team1':'Virginia Tech', 'team2':'Georgia Tech', 'team1_score':17, 'team2_score':10, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':172,'number':2,'team1':'Virginia', 'team2':'Pittsburgh', 'team1_score':3, 'team2_score':14, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':173,'number':3,'team1':'Iowa', 'team2':'Minnesota', 'team1_score':23, 'team2_score':7, 'favored':'team1','spread':1.5,'state':'final'})
        self.transactions.append({'recno':174,'number':4,'team1':'Oklahoma', 'team2':'Notre Dame', 'team1_score':35, 'team2_score':21, 'favored':'team1','spread':3.5,'state':'final'})
        self.transactions.append({'recno':175,'number':5,'team1':'South Carolina', 'team2':'UCF', 'team1_score':28, 'team2_score':25, 'favored':'team1','spread':7.5,'state':'final'})
        self.transactions.append({'recno':176,'number':6,'team1':'Arizona', 'team2':'Washington', 'team1_score':13, 'team2_score':31, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':177,'number':7,'team1':'LSU', 'team2':'Georgia', 'team1_score':41, 'team2_score':44, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':178,'number':8,'team1':'Colorado', 'team2':'Oregon State', 'team1_score':17, 'team2_score':44, 'favored':'team2','spread':10.5,'state':'final'})
        self.transactions.append({'recno':179,'number':9,'team1':'Mississippi', 'team2':'Alabama', 'team1_score':0, 'team2_score':25, 'favored':'team2','spread':16.5,'state':'final'})
        self.transactions.append({'recno':180,'number':10,'team1':'Wisconsin', 'team2':'Ohio State', 'team1_score':24, 'team2_score':31, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':181,'number':1,'team1':'UCLA', 'team2':'Utah', 'team1_score':34, 'team2_score':27, 'favored':'team1','spread':4.5,'state':'final'})
        self.transactions.append({'recno':182,'number':2,'team1':'Georgia', 'team2':'Tennessee', 'team1_score':34, 'team2_score':31, 'favored':'team1','spread':10.5,'state':'final'})
        self.transactions.append({'recno':183,'number':3,'team1':'Clemson', 'team2':'Syracuse', 'team1_score':49, 'team2_score':14, 'favored':'team1','spread':13.5,'state':'final'})
        self.transactions.append({'recno':184,'number':4,'team1':'Georgia Tech', 'team2':'Miami-Florida', 'team1_score':30, 'team2_score':45, 'favored':'team2','spread':4.5,'state':'final'})
        self.transactions.append({'recno':185,'number':5,'team1':'North Carolina', 'team2':'Virginia Tech', 'team1_score':17, 'team2_score':27, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':186,'number':6,'team1':'Arizona State', 'team2':'Notre Dame', 'team1_score':34, 'team2_score':37, 'favored':'team1','spread':5.5,'state':'final'})
        self.transactions.append({'recno':187,'number':7,'team1':'Washington', 'team2':'Stanford', 'team1_score':28, 'team2_score':31, 'favored':'team2','spread':6.5,'state':'final'})
        self.transactions.append({'recno':188,'number':8,'team1':'Mississippi', 'team2':'Auburn', 'team1_score':22, 'team2_score':30, 'favored':'team1','spread':3.5,'state':'final'})
        self.transactions.append({'recno':189,'number':9,'team1':'Ohio State', 'team2':'Northwestern', 'team1_score':40, 'team2_score':30, 'favored':'team1','spread':5.5,'state':'final'})
        self.transactions.append({'recno':190,'number':10,'team1':'Maryland', 'team2':'Florida State', 'team1_score':0, 'team2_score':63, 'favored':'team2','spread':14.5,'state':'final'})
        self.transactions.append({'recno':191,'number':1,'team1':'Rutgers', 'team2':'Louisville', 'team1_score':10, 'team2_score':24, 'favored':'team2','spread':17.5,'state':'final'})
        self.transactions.append({'recno':192,'number':2,'team1':'Oklahoma', 'team2':'Texas', 'team1_score':20, 'team2_score':36, 'favored':'team1','spread':14.5,'state':'final'})
        self.transactions.append({'recno':193,'number':3,'team1':'Texas A&M', 'team2':'Mississippi', 'team1_score':41, 'team2_score':38, 'favored':'team1','spread':7.5,'state':'final'})
        self.transactions.append({'recno':194,'number':4,'team1':'Georgia Tech', 'team2':'BYU', 'team1_score':20, 'team2_score':38, 'favored':'team2','spread':6.5,'state':'final'})
        self.transactions.append({'recno':195,'number':5,'team1':'Missouri', 'team2':'Georgia', 'team1_score':41, 'team2_score':26, 'favored':'team2','spread':9.5,'state':'final'})
        self.transactions.append({'recno':196,'number':6,'team1':'Florida', 'team2':'LSU', 'team1_score':6, 'team2_score':17, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':197,'number':7,'team1':'Syracuse', 'team2':'NC State', 'team1_score':24, 'team2_score':10, 'favored':'team2','spread':5.5,'state':'final'})
        self.transactions.append({'recno':198,'number':8,'team1':'South Carolina', 'team2':'Arkansas', 'team1_score':52, 'team2_score':7, 'favored':'team1','spread':5.5,'state':'final'})
        self.transactions.append({'recno':199,'number':9,'team1':'Michigan', 'team2':'Penn State', 'team1_score':40, 'team2_score':43, 'favored':'team1','spread':3.5,'state':'final'})
        self.transactions.append({'recno':200,'number':10,'team1':'Oregon', 'team2':'Washington', 'team1_score':45, 'team2_score':24, 'favored':'team1','spread':14.5,'state':'final'})
        self.transactions.append({'recno':201,'number':1,'team1':'Miami-Florida', 'team2':'North Carolina', 'team1_score':27, 'team2_score':23, 'favored':'team1','spread':7.5,'state':'final'})
        self.transactions.append({'recno':202,'number':2,'team1':'UCF', 'team2':'Louisville', 'team1_score':38, 'team2_score':35, 'favored':'team2','spread':10.5,'state':'final'})
        self.transactions.append({'recno':203,'number':3,'team1':'LSU', 'team2':'Mississippi', 'team1_score':24, 'team2_score':27, 'favored':'team1','spread':7.5,'state':'final'})
        self.transactions.append({'recno':204,'number':4,'team1':'Florida', 'team2':'Missouri', 'team1_score':17, 'team2_score':36, 'favored':'team1','spread':3.5,'state':'final'})
        self.transactions.append({'recno':205,'number':5,'team1':'Washington', 'team2':'Arizona State', 'team1_score':24, 'team2_score':53, 'favored':'team2','spread':3.5,'state':'final'})
        self.transactions.append({'recno':206,'number':6,'team1':'TCU', 'team2':'Oklahoma State', 'team1_score':10, 'team2_score':24, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':207,'number':7,'team1':'UCLA', 'team2':'Stanford', 'team1_score':10, 'team2_score':24, 'favored':'team2','spread':5.5,'state':'final'})
        self.transactions.append({'recno':208,'number':8,'team1':'Auburn', 'team2':'Texas A&M', 'team1_score':45, 'team2_score':41, 'favored':'team2','spread':13.5,'state':'final'})
        self.transactions.append({'recno':209,'number':9,'team1':'South Carolina', 'team2':'Tennessee', 'team1_score':21, 'team2_score':23, 'favored':'team1','spread':7.5,'state':'final'})
        self.transactions.append({'recno':210,'number':10,'team1':'Florida State', 'team2':'Clemson', 'team1_score':51, 'team2_score':14, 'favored':'team1','spread':3.5,'state':'final'})
        self.transactions.append({'recno':211,'number':1,'team1':'Kentucky', 'team2':'Mississippi State', 'team1_score':22, 'team2_score':28, 'favored':'team2','spread':10.5,'state':'final'})
        self.transactions.append({'recno':212,'number':2,'team1':'Northwestern', 'team2':'Iowa', 'team1_score':10, 'team2_score':17, 'favored':'team2','spread':4.5,'state':'final'})
        self.transactions.append({'recno':213,'number':3,'team1':'Georgia Tech', 'team2':'Virginia', 'team1_score':35, 'team2_score':25, 'favored':'team1','spread':9.5,'state':'final'})
        self.transactions.append({'recno':214,'number':4,'team1':'Clemson', 'team2':'Maryland', 'team1_score':40, 'team2_score':27, 'favored':'team1','spread':13.5,'state':'final'})
        self.transactions.append({'recno':215,'number':5,'team1':'UCLA', 'team2':'Oregon', 'team1_score':14, 'team2_score':42, 'favored':'team2','spread':22.5,'state':'final'})
        self.transactions.append({'recno':216,'number':6,'team1':'Stanford', 'team2':'Oregon State', 'team1_score':20, 'team2_score':12, 'favored':'team1','spread':5.5,'state':'final'})
        self.transactions.append({'recno':217,'number':7,'team1':'Texas', 'team2':'TCU', 'team1_score':30, 'team2_score':7, 'favored':'team2','spread':1.5,'state':'final'})
        self.transactions.append({'recno':218,'number':8,'team1':'South Carolina', 'team2':'Missouri', 'team1_score':27, 'team2_score':24, 'favored':'team2','spread':5.5,'state':'final'})
        self.transactions.append({'recno':219,'number':9,'team1':'Penn State', 'team2':'Ohio State', 'team1_score':14, 'team2_score':63, 'favored':'team2','spread':14.5,'state':'final'})
        self.transactions.append({'recno':220,'number':10,'team1':'Texas Tech', 'team2':'Oklahoma', 'team1_score':30, 'team2_score':38, 'favored':'team2','spread':7.5,'state':'final'})
        self.transactions.append({'recno':221,'number':1,'team1':'Southern Cal', 'team2':'Oregon State', 'team1_score':31, 'team2_score':14, 'favored':'team2','spread':5.5,'state':'final'})
        self.transactions.append({'recno':222,'number':2,'team1':'Virginia Tech', 'team2':'Boston College', 'team1_score':27, 'team2_score':24, 'favored':'team1','spread':5.5,'state':'final'})
        self.transactions.append({'recno':223,'number':3,'team1':'Pittsburgh', 'team2':'Georgia Tech', 'team1_score':10, 'team2_score':21, 'favored':'team2','spread':9.5,'state':'final'})
        self.transactions.append({'recno':224,'number':4,'team1':'Tennessee', 'team2':'Missouri', 'team1_score':3, 'team2_score':31, 'favored':'team2','spread':11.5,'state':'final'})
        self.transactions.append({'recno':225,'number':5,'team1':'Georgia', 'team2':'Florida', 'team1_score':23, 'team2_score':20, 'favored':'team1','spread':2.5,'state':'final'})
        self.transactions.append({'recno':226,'number':6,'team1':'Miami-Florida', 'team2':'Florida State', 'team1_score':14, 'team2_score':41, 'favored':'team2','spread':21.5,'state':'final'})
        self.transactions.append({'recno':227,'number':7,'team1':'Michigan', 'team2':'Michigan State', 'team1_score':6, 'team2_score':29, 'favored':'team2','spread':4.5,'state':'final'})
        self.transactions.append({'recno':228,'number':8,'team1':'North Carolina', 'team2':'NC State', 'team1_score':27, 'team2_score':19, 'favored':'team1','spread':3.5,'state':'final'})
        self.transactions.append({'recno':229,'number':9,'team1':'Mississippi State', 'team2':'South Carolina', 'team1_score':16, 'team2_score':34, 'favored':'team2','spread':12.5,'state':'final'})
        self.transactions.append({'recno':230,'number':10,'team1':'Oklahoma State', 'team2':'Texas Tech', 'team1_score':52, 'team2_score':34, 'favored':'team2','spread':1.5,'state':'final'})
        self.transactions.append({'recno':231,'number':1,'team1':'Oklahoma', 'team2':'Baylor', 'team1_score':12, 'team2_score':41, 'favored':'team2','spread':14.5,'state':'final'})
        self.transactions.append({'recno':232,'number':2,'team1':'LSU', 'team2':'Alabama', 'team1_score':17, 'team2_score':38, 'favored':'team2','spread':11.5,'state':'final'})
        self.transactions.append({'recno':233,'number':3,'team1':'Penn State', 'team2':'Minnesota', 'team1_score':10, 'team2_score':24, 'favored':'team2','spread':2.5,'state':'final'})
        self.transactions.append({'recno':234,'number':4,'team1':'Virginia Tech', 'team2':'Miami-Florida', 'team1_score':42, 'team2_score':24, 'favored':'team2','spread':6.5,'state':'final'})
        self.transactions.append({'recno':235,'number':5,'team1':'Fresno State', 'team2':'Wyoming', 'team1_score':48, 'team2_score':10, 'favored':'team1','spread':10.5,'state':'final'})
        self.transactions.append({'recno':236,'number':6,'team1':'Nebraska', 'team2':'Michigan', 'team1_score':17, 'team2_score':13, 'favored':'team2','spread':6.5,'state':'final'})
        self.transactions.append({'recno':237,'number':7,'team1':'Notre Dame', 'team2':'Pittsburgh', 'team1_score':21, 'team2_score':28, 'favored':'team1','spread':3.5,'state':'final'})
        self.transactions.append({'recno':238,'number':8,'team1':'Auburn', 'team2':'Tennessee', 'team1_score':55, 'team2_score':23, 'favored':'team1','spread':7.5,'state':'final'})
        self.transactions.append({'recno':239,'number':9,'team1':'Kansas State', 'team2':'Texas Tech', 'team1_score':49, 'team2_score':26, 'favored':'team2','spread':2.5,'state':'final'})
        self.transactions.append({'recno':240,'number':10,'team1':'Oregon', 'team2':'Stanford', 'team1_score':20, 'team2_score':26, 'favored':'team1','spread':10.5,'state':'final'})
        self.transactions.append({'recno':241,'number':1,'team1':'Georgia Tech', 'team2':'Clemson', 'team1_score':None, 'team2_score':None, 'favored':'team2','spread':10.5,'state':'not_started'})
        self.transactions.append({'recno':242,'number':2,'team1':'Washington', 'team2':'UCLA', 'team1_score':None, 'team2_score':None, 'favored':'team2','spread':2.5,'state':'not_started'})
        self.transactions.append({'recno':243,'number':3,'team1':'Michigan State', 'team2':'Nebraska', 'team1_score':None, 'team2_score':None, 'favored':'team1','spread':6.5,'state':'not_started'})
        self.transactions.append({'recno':244,'number':4,'team1':'Florida', 'team2':'South Carolina', 'team1_score':None, 'team2_score':None, 'favored':'team2','spread':13.5,'state':'not_started'})
        self.transactions.append({'recno':245,'number':5,'team1':'Georgia', 'team2':'Auburn', 'team1_score':None, 'team2_score':None, 'favored':'team2','spread':4.5,'state':'not_started'})
        self.transactions.append({'recno':246,'number':6,'team1':'Stanford', 'team2':'Southern Cal', 'team1_score':None, 'team2_score':None, 'favored':'team1','spread':3.5,'state':'not_started'})
        self.transactions.append({'recno':247,'number':7,'team1':'Oklahoma State', 'team2':'Texas', 'team1_score':None, 'team2_score':None, 'favored':'team1','spread':2.5,'state':'not_started'})
        self.transactions.append({'recno':248,'number':8,'team1':'West Virginia', 'team2':'Kansas', 'team1_score':None, 'team2_score':None, 'favored':'team1','spread':6.5,'state':'not_started'})
        self.transactions.append({'recno':249,'number':9,'team1':'Utah', 'team2':'Oregon', 'team1_score':None, 'team2_score':None, 'favored':'team2','spread':10.5,'state':'not_started'})
        self.transactions.append({'recno':250,'number':10,'team1':'Miami-Florida', 'team2':'Duke', 'team1_score':None, 'team2_score':None, 'favored':'team1','spread':2.5,'state':'not_started'})

