from models.teams import *

class LoadTeams:

    def __init__(self):
        self.load()

    def num_transactions(self):
        return len(self.transactions)

    def run_transactions(self,txn_range):
        last_index = self.num_transactions() - 1
        for i in txn_range:
            if i > last_index:
                break
            d = self.transactions[i]
            self.add_team(name=d['name'],conference=d['conference'])

    def add_team(self,name,conference):
        t = Team(name=name,conference=conference)
        key = t.put()

    def load(self):
        self.transactions = []
        self.transactions.append({'name':'Clemson','conference':'Atlantic Coast'})
        self.transactions.append({'name':'Florida State','conference':'Atlantic Coast'})
        self.transactions.append({'name':'North Carolina','conference':'Atlantic Coast'})
        self.transactions.append({'name':'Pittsburgh','conference':'Atlantic Coast'})
        self.transactions.append({'name':'Syracuse','conference':'Atlantic Coast'})
        self.transactions.append({'name':'Boston College','conference':'Atlantic Coast'})
        self.transactions.append({'name':'Duke','conference':'Atlantic Coast'})
        self.transactions.append({'name':'Georgia Tech','conference':'Atlantic Coast'})
        self.transactions.append({'name':'Maryland','conference':'Atlantic Coast'})
        self.transactions.append({'name':'Miami-Florida','conference':'Atlantic Coast'})
        self.transactions.append({'name':'NC State','conference':'Atlantic Coast'})
        self.transactions.append({'name':'Virginia','conference':'Atlantic Coast'})
        self.transactions.append({'name':'Virginia Tech','conference':'Atlantic Coast'})
        self.transactions.append({'name':'Wake Forest','conference':'Atlantic Coast'})
        self.transactions.append({'name':'Oklahoma State','conference':'Big 12'})
        self.transactions.append({'name':'TCU','conference':'Big 12'})
        self.transactions.append({'name':'Baylor','conference':'Big 12'})
        self.transactions.append({'name':'Iowa State','conference':'Big 12'})
        self.transactions.append({'name':'Kansas','conference':'Big 12'})
        self.transactions.append({'name':'Kansas State','conference':'Big 12'})
        self.transactions.append({'name':'Oklahoma','conference':'Big 12'})
        self.transactions.append({'name':'Texas','conference':'Big 12'})
        self.transactions.append({'name':'Texas Tech','conference':'Big 12'})
        self.transactions.append({'name':'West Virginia','conference':'Big 12'})
        self.transactions.append({'name':'Cincinnati','conference':'American Athletic'})
        self.transactions.append({'name':'Connecticut','conference':'American Athletic'})
        self.transactions.append({'name':'Houston','conference':'American Athletic'})
        self.transactions.append({'name':'Louisville','conference':'American Athletic'})
        self.transactions.append({'name':'Memphis','conference':'American Athletic'})
        self.transactions.append({'name':'Rutgers','conference':'American Athletic'})
        self.transactions.append({'name':'South Florida','conference':'American Athletic'})
        self.transactions.append({'name':'Southern Methodist','conference':'American Athletic'})
        self.transactions.append({'name':'Temple','conference':'American Athletic'})
        self.transactions.append({'name':'UCF','conference':'American Athletic'})
        self.transactions.append({'name':'Northwestern','conference':'Big Ten'})
        self.transactions.append({'name':'Penn State','conference':'Big Ten'})
        self.transactions.append({'name':'Illinois','conference':'Big Ten'})
        self.transactions.append({'name':'Indiana','conference':'Big Ten'})
        self.transactions.append({'name':'Iowa','conference':'Big Ten'})
        self.transactions.append({'name':'Michigan','conference':'Big Ten'})
        self.transactions.append({'name':'Michigan State','conference':'Big Ten'})
        self.transactions.append({'name':'Minnesota','conference':'Big Ten'})
        self.transactions.append({'name':'Nebraska','conference':'Big Ten'})
        self.transactions.append({'name':'Ohio State','conference':'Big Ten'})
        self.transactions.append({'name':'Purdue','conference':'Big Ten'})
        self.transactions.append({'name':'Wisconsin','conference':'Big Ten'})
        self.transactions.append({'name':'East Carolina','conference':'Conference USA'})
        self.transactions.append({'name':'Florida Atlantic','conference':'Conference USA'})
        self.transactions.append({'name':'Florida International','conference':'Conference USA'})
        self.transactions.append({'name':'Louisiana Tech','conference':'Conference USA'})
        self.transactions.append({'name':'Marshall','conference':'Conference USA'})
        self.transactions.append({'name':'Middle Tennessee','conference':'Conference USA'})
        self.transactions.append({'name':'North Texas','conference':'Conference USA'})
        self.transactions.append({'name':'Rice','conference':'Conference USA'})
        self.transactions.append({'name':'Southern Miss','conference':'Conference USA'})
        self.transactions.append({'name':'Texas-El Paso','conference':'Conference USA'})
        self.transactions.append({'name':'Texas-San Antonio','conference':'Conference USA'})
        self.transactions.append({'name':'Tulane','conference':'Conference USA'})
        self.transactions.append({'name':'Tulsa','conference':'Conference USA'})
        self.transactions.append({'name':'UAB','conference':'Conference USA'})
        self.transactions.append({'name':'Army','conference':'Independents'})
        self.transactions.append({'name':'BYU','conference':'Independents'})
        self.transactions.append({'name':'Idaho','conference':'Independents'})
        self.transactions.append({'name':'Navy','conference':'Independents'})
        self.transactions.append({'name':'New Mexico State','conference':'Independents'})
        self.transactions.append({'name':'Notre Dame','conference':'Independents'})
        self.transactions.append({'name':'Old Dominion','conference':'Independents'})
        self.transactions.append({'name':'Akron','conference':'Mid American'})
        self.transactions.append({'name':'Ball State','conference':'Mid American'})
        self.transactions.append({'name':'Bowling Green','conference':'Mid American'})
        self.transactions.append({'name':'Buffalo','conference':'Mid American'})
        self.transactions.append({'name':'Central Michigan','conference':'Mid American'})
        self.transactions.append({'name':'Eastern Michigan','conference':'Mid American'})
        self.transactions.append({'name':'Kent State','conference':'Mid American'})
        self.transactions.append({'name':'Massachusetts','conference':'Mid American'})
        self.transactions.append({'name':'Miami-Ohio','conference':'Mid American'})
        self.transactions.append({'name':'Northern Illinois','conference':'Mid American'})
        self.transactions.append({'name':'Ohio','conference':'Mid American'})
        self.transactions.append({'name':'Toledo','conference':'Mid American'})
        self.transactions.append({'name':'Western Michigan','conference':'Mid American'})
        self.transactions.append({'name':'Boise State','conference':'Mountain West'})
        self.transactions.append({'name':'Colorado State','conference':'Mountain West'})
        self.transactions.append({'name':'Utah State','conference':'Mountain West'})
        self.transactions.append({'name':'Air Force','conference':'Mountain West'})
        self.transactions.append({'name':'Fresno State','conference':'Mountain West'})
        self.transactions.append({'name':'Hawaii','conference':'Mountain West'})
        self.transactions.append({'name':'Nevada','conference':'Mountain West'})
        self.transactions.append({'name':'New Mexico','conference':'Mountain West'})
        self.transactions.append({'name':'San Diego State','conference':'Mountain West'})
        self.transactions.append({'name':'San Jose State','conference':'Mountain West'})
        self.transactions.append({'name':'UNLV','conference':'Mountain West'})
        self.transactions.append({'name':'Wyoming','conference':'Mountain West'})
        self.transactions.append({'name':'California','conference':'Pacific 12'})
        self.transactions.append({'name':'Colorado','conference':'Pacific 12'})
        self.transactions.append({'name':'Utah','conference':'Pacific 12'})
        self.transactions.append({'name':'Washington','conference':'Pacific 12'})
        self.transactions.append({'name':'Arizona','conference':'Pacific 12'})
        self.transactions.append({'name':'Arizona State','conference':'Pacific 12'})
        self.transactions.append({'name':'Oregon','conference':'Pacific 12'})
        self.transactions.append({'name':'Oregon State','conference':'Pacific 12'})
        self.transactions.append({'name':'Southern Cal','conference':'Pacific 12'})
        self.transactions.append({'name':'Stanford','conference':'Pacific 12'})
        self.transactions.append({'name':'UCLA','conference':'Pacific 12'})
        self.transactions.append({'name':'Washington State','conference':'Pacific 12'})
        self.transactions.append({'name':'Georgia','conference':'Southeastern'})
        self.transactions.append({'name':'LSU','conference':'Southeastern'})
        self.transactions.append({'name':'Mississippi State','conference':'Southeastern'})
        self.transactions.append({'name':'South Carolina','conference':'Southeastern'})
        self.transactions.append({'name':'Alabama','conference':'Southeastern'})
        self.transactions.append({'name':'Arkansas','conference':'Southeastern'})
        self.transactions.append({'name':'Auburn','conference':'Southeastern'})
        self.transactions.append({'name':'Florida','conference':'Southeastern'})
        self.transactions.append({'name':'Kentucky','conference':'Southeastern'})
        self.transactions.append({'name':'Mississippi','conference':'Southeastern'})
        self.transactions.append({'name':'Missouri','conference':'Southeastern'})
        self.transactions.append({'name':'Tennessee','conference':'Southeastern'})
        self.transactions.append({'name':'Texas A&M','conference':'Southeastern'})
        self.transactions.append({'name':'Vanderbilt','conference':'Southeastern'})
        self.transactions.append({'name':'Arkansas State','conference':'Sun Belt'})
        self.transactions.append({'name':'Georgia State','conference':'Sun Belt'})
        self.transactions.append({'name':'Louisiana Lafayette','conference':'Sun Belt'})
        self.transactions.append({'name':'Louisiana Monroe','conference':'Sun Belt'})
        self.transactions.append({'name':'South Alabama','conference':'Sun Belt'})
        self.transactions.append({'name':'Texas State','conference':'Sun Belt'})
        self.transactions.append({'name':'Troy','conference':'Sun Belt'})
        self.transactions.append({'name':'Western Kentucky','conference':'Sun Belt'})
        self.transactions.append({'name':'Cal Poly','conference':'Big Sky'})
        self.transactions.append({'name':'Eastern Washington','conference':'Big Sky'})
        self.transactions.append({'name':'Idaho State','conference':'Big Sky'})
        self.transactions.append({'name':'Montana','conference':'Big Sky'})
        self.transactions.append({'name':'Montana State','conference':'Big Sky'})
        self.transactions.append({'name':'North Dakota','conference':'Big Sky'})
        self.transactions.append({'name':'Northern Arizona','conference':'Big Sky'})
        self.transactions.append({'name':'Northern Colorado','conference':'Big Sky'})
        self.transactions.append({'name':'Portland State','conference':'Big Sky'})
        self.transactions.append({'name':'Sacramento State','conference':'Big Sky'})
        self.transactions.append({'name':'Southern Utah','conference':'Big Sky'})
        self.transactions.append({'name':'UC Davis','conference':'Big Sky'})
        self.transactions.append({'name':'Weber State','conference':'Big Sky'})
        self.transactions.append({'name':'Charleston Southern','conference':'Big South'})
        self.transactions.append({'name':'Coastal Carolina','conference':'Big South'})
        self.transactions.append({'name':'Gardner-Webb','conference':'Big South'})
        self.transactions.append({'name':'Liberty','conference':'Big South'})
        self.transactions.append({'name':'Presbyterian','conference':'Big South'})
        self.transactions.append({'name':'Virginia Military Institute','conference':'Big South'})
        self.transactions.append({'name':'Albany','conference':'CAA'})
        self.transactions.append({'name':'Delaware','conference':'CAA'})
        self.transactions.append({'name':'James Madison','conference':'CAA'})
        self.transactions.append({'name':'Maine','conference':'CAA'})
        self.transactions.append({'name':'New Hampshire','conference':'CAA'})
        self.transactions.append({'name':'Rhode Island','conference':'CAA'})
        self.transactions.append({'name':'Richmond','conference':'CAA'})
        self.transactions.append({'name':'Stony Brook','conference':'CAA'})
        self.transactions.append({'name':'Towson','conference':'CAA'})
        self.transactions.append({'name':'Villanova','conference':'CAA'})
        self.transactions.append({'name':'William & Mary','conference':'CAA'})
        self.transactions.append({'name':'Abilene Christian','conference':'FCS Independents'})
        self.transactions.append({'name':'Charlotte','conference':'FCS Independents'})
        self.transactions.append({'name':'Houston Baptist','conference':'FCS Independents'})
        self.transactions.append({'name':'Incarnate Word','conference':'FCS Independents'})
        self.transactions.append({'name':'Monmouth','conference':'FCS Independents'})
        self.transactions.append({'name':'Brown','conference':'Ivy'})
        self.transactions.append({'name':'Columbia','conference':'Ivy'})
        self.transactions.append({'name':'Cornell','conference':'Ivy'})
        self.transactions.append({'name':'Dartmouth','conference':'Ivy'})
        self.transactions.append({'name':'Harvard','conference':'Ivy'})
        self.transactions.append({'name':'Pennsylvania','conference':'Ivy'})
        self.transactions.append({'name':'Princeton','conference':'Ivy'})
        self.transactions.append({'name':'Yale','conference':'Ivy'})
        self.transactions.append({'name':'Bethune-Cookman','conference':'MEAC'})
        self.transactions.append({'name':'Delaware State','conference':'MEAC'})
        self.transactions.append({'name':'Florida A&M','conference':'MEAC'})
        self.transactions.append({'name':'Hampton','conference':'MEAC'})
        self.transactions.append({'name':'Howard','conference':'MEAC'})
        self.transactions.append({'name':'Morgan State','conference':'MEAC'})
        self.transactions.append({'name':'NC Central','conference':'MEAC'})
        self.transactions.append({'name':'Norfolk State','conference':'MEAC'})
        self.transactions.append({'name':'North Carolina A&T','conference':'MEAC'})
        self.transactions.append({'name':'Savannah State','conference':'MEAC'})
        self.transactions.append({'name':'South Carolina State','conference':'MEAC'})
        self.transactions.append({'name':'Illinois State','conference':'Missouri Valley'})
        self.transactions.append({'name':'Indiana State','conference':'Missouri Valley'})
        self.transactions.append({'name':'Missouri State','conference':'Missouri Valley'})
        self.transactions.append({'name':'North Dakota State','conference':'Missouri Valley'})
        self.transactions.append({'name':'Northern Iowa','conference':'Missouri Valley'})
        self.transactions.append({'name':'South Dakota','conference':'Missouri Valley'})
        self.transactions.append({'name':'South Dakota State','conference':'Missouri Valley'})
        self.transactions.append({'name':'Southern Illinois','conference':'Missouri Valley'})
        self.transactions.append({'name':'Western Illinois','conference':'Missouri Valley'})
        self.transactions.append({'name':'Youngstown State','conference':'Missouri Valley'})
        self.transactions.append({'name':'Bryant','conference':'Northeast'})
        self.transactions.append({'name':'Central Connecticut State','conference':'Northeast'})
        self.transactions.append({'name':'Duquesne','conference':'Northeast'})
        self.transactions.append({'name':'Robert Morris','conference':'Northeast'})
        self.transactions.append({'name':'Sacred Heart','conference':'Northeast'})
        self.transactions.append({'name':'St. Francis (PA)','conference':'Northeast'})
        self.transactions.append({'name':'Wagner','conference':'Northeast'})
        self.transactions.append({'name':'Austin Peay','conference':'Ohio Valley'})
        self.transactions.append({'name':'Eastern Illinois','conference':'Ohio Valley'})
        self.transactions.append({'name':'Eastern Kentucky','conference':'Ohio Valley'})
        self.transactions.append({'name':'Jacksonville State','conference':'Ohio Valley'})
        self.transactions.append({'name':'Murray State','conference':'Ohio Valley'})
        self.transactions.append({'name':'Southeast Missouri State','conference':'Ohio Valley'})
        self.transactions.append({'name':'Tennessee State','conference':'Ohio Valley'})
        self.transactions.append({'name':'Tennessee Tech','conference':'Ohio Valley'})
        self.transactions.append({'name':'Tennessee-Martin','conference':'Ohio Valley'})
        self.transactions.append({'name':'Bucknell','conference':'Patriot League'})
        self.transactions.append({'name':'Colgate','conference':'Patriot League'})
        self.transactions.append({'name':'Fordham','conference':'Patriot League'})
        self.transactions.append({'name':'Georgetown','conference':'Patriot League'})
        self.transactions.append({'name':'Holy Cross','conference':'Patriot League'})
        self.transactions.append({'name':'Lafayette','conference':'Patriot League'})
        self.transactions.append({'name':'Lehigh','conference':'Patriot League'})
        self.transactions.append({'name':'Butler','conference':'Pioneer'})
        self.transactions.append({'name':'Campbell','conference':'Pioneer'})
        self.transactions.append({'name':'Davidson','conference':'Pioneer'})
        self.transactions.append({'name':'Dayton','conference':'Pioneer'})
        self.transactions.append({'name':'Drake','conference':'Pioneer'})
        self.transactions.append({'name':'Jacksonville','conference':'Pioneer'})
        self.transactions.append({'name':'Marist','conference':'Pioneer'})
        self.transactions.append({'name':'Mercer','conference':'Pioneer'})
        self.transactions.append({'name':'Morehead State','conference':'Pioneer'})
        self.transactions.append({'name':'San Diego','conference':'Pioneer'})
        self.transactions.append({'name':'Stetson','conference':'Pioneer'})
        self.transactions.append({'name':'Valparaiso','conference':'Pioneer'})
        self.transactions.append({'name':'Appalachian State','conference':'Southern'})
        self.transactions.append({'name':'Chattanooga','conference':'Southern'})
        self.transactions.append({'name':'Citadel','conference':'Southern'})
        self.transactions.append({'name':'Elon','conference':'Southern'})
        self.transactions.append({'name':'Furman','conference':'Southern'})
        self.transactions.append({'name':'Georgia Southern','conference':'Southern'})
        self.transactions.append({'name':'Samford','conference':'Southern'})
        self.transactions.append({'name':'Western Carolina','conference':'Southern'})
        self.transactions.append({'name':'Wofford','conference':'Southern'})
        self.transactions.append({'name':'Central Arkansas','conference':'Southland'})
        self.transactions.append({'name':'Lamar','conference':'Southland'})
        self.transactions.append({'name':'McNeese State','conference':'Southland'})
        self.transactions.append({'name':'Nicholls State','conference':'Southland'})
        self.transactions.append({'name':'Northwestern State','conference':'Southland'})
        self.transactions.append({'name':'Sam Houston State','conference':'Southland'})
        self.transactions.append({'name':'Southeastern Louisiana','conference':'Southland'})
        self.transactions.append({'name':'Stephen F. Austin','conference':'Southland'})
        self.transactions.append({'name':'Alabama A&M','conference':'SWAC'})
        self.transactions.append({'name':'Alabama State','conference':'SWAC'})
        self.transactions.append({'name':'Alcorn State','conference':'SWAC'})
        self.transactions.append({'name':'Arkansas-Pine Bluff','conference':'SWAC'})
        self.transactions.append({'name':'Grambling State','conference':'SWAC'})
        self.transactions.append({'name':'Jackson State','conference':'SWAC'})
        self.transactions.append({'name':'Mississippi Valley State','conference':'SWAC'})
        self.transactions.append({'name':'Prairie View A&M','conference':'SWAC'})
        self.transactions.append({'name':'Southern University','conference':'SWAC'})
        self.transactions.append({'name':'Texas Southern','conference':'SWAC'})

