from teams import *

class LoadTeams:

    def add_team(self,name,conference):
        t = Team(name=name,conference=conference)
        return t.put()

    def load(self):
        lookup = dict()
        lookup['Clemson'] = self.add_team(name='Clemson',conference='Atlantic Coast')
        lookup['Florida State'] = self.add_team(name='Florida State',conference='Atlantic Coast')
        lookup['North Carolina'] = self.add_team(name='North Carolina',conference='Atlantic Coast')
        lookup['Pittsburgh'] = self.add_team(name='Pittsburgh',conference='Atlantic Coast')
        lookup['Syracuse'] = self.add_team(name='Syracuse',conference='Atlantic Coast')
        lookup['Boston College'] = self.add_team(name='Boston College',conference='Atlantic Coast')
        lookup['Duke'] = self.add_team(name='Duke',conference='Atlantic Coast')
        lookup['Georgia Tech'] = self.add_team(name='Georgia Tech',conference='Atlantic Coast')
        lookup['Maryland'] = self.add_team(name='Maryland',conference='Atlantic Coast')
        lookup['Miami-Florida'] = self.add_team(name='Miami-Florida',conference='Atlantic Coast')
        lookup['NC State'] = self.add_team(name='NC State',conference='Atlantic Coast')
        lookup['Virginia'] = self.add_team(name='Virginia',conference='Atlantic Coast')
        lookup['Virginia Tech'] = self.add_team(name='Virginia Tech',conference='Atlantic Coast')
        lookup['Wake Forest'] = self.add_team(name='Wake Forest',conference='Atlantic Coast')
        lookup['Oklahoma State'] = self.add_team(name='Oklahoma State',conference='Big 12')
        lookup['TCU'] = self.add_team(name='TCU',conference='Big 12')
        lookup['Baylor'] = self.add_team(name='Baylor',conference='Big 12')
        lookup['Iowa State'] = self.add_team(name='Iowa State',conference='Big 12')
        lookup['Kansas'] = self.add_team(name='Kansas',conference='Big 12')
        lookup['Kansas State'] = self.add_team(name='Kansas State',conference='Big 12')
        lookup['Oklahoma'] = self.add_team(name='Oklahoma',conference='Big 12')
        lookup['Texas'] = self.add_team(name='Texas',conference='Big 12')
        lookup['Texas Tech'] = self.add_team(name='Texas Tech',conference='Big 12')
        lookup['West Virginia'] = self.add_team(name='West Virginia',conference='Big 12')
        lookup['Cincinnati'] = self.add_team(name='Cincinnati',conference='American Athletic')
        lookup['Connecticut'] = self.add_team(name='Connecticut',conference='American Athletic')
        lookup['Houston'] = self.add_team(name='Houston',conference='American Athletic')
        lookup['Louisville'] = self.add_team(name='Louisville',conference='American Athletic')
        lookup['Memphis'] = self.add_team(name='Memphis',conference='American Athletic')
        lookup['Rutgers'] = self.add_team(name='Rutgers',conference='American Athletic')
        lookup['South Florida'] = self.add_team(name='South Florida',conference='American Athletic')
        lookup['Southern Methodist'] = self.add_team(name='Southern Methodist',conference='American Athletic')
        lookup['Temple'] = self.add_team(name='Temple',conference='American Athletic')
        lookup['UCF'] = self.add_team(name='UCF',conference='American Athletic')
        lookup['Northwestern'] = self.add_team(name='Northwestern',conference='Big Ten')
        lookup['Penn State'] = self.add_team(name='Penn State',conference='Big Ten')
        lookup['Illinois'] = self.add_team(name='Illinois',conference='Big Ten')
        lookup['Indiana'] = self.add_team(name='Indiana',conference='Big Ten')
        lookup['Iowa'] = self.add_team(name='Iowa',conference='Big Ten')
        lookup['Michigan'] = self.add_team(name='Michigan',conference='Big Ten')
        lookup['Michigan State'] = self.add_team(name='Michigan State',conference='Big Ten')
        lookup['Minnesota'] = self.add_team(name='Minnesota',conference='Big Ten')
        lookup['Nebraska'] = self.add_team(name='Nebraska',conference='Big Ten')
        lookup['Ohio State'] = self.add_team(name='Ohio State',conference='Big Ten')
        lookup['Purdue'] = self.add_team(name='Purdue',conference='Big Ten')
        lookup['Wisconsin'] = self.add_team(name='Wisconsin',conference='Big Ten')
        lookup['East Carolina'] = self.add_team(name='East Carolina',conference='Conference USA')
        lookup['Florida Atlantic'] = self.add_team(name='Florida Atlantic',conference='Conference USA')
        lookup['Florida International'] = self.add_team(name='Florida International',conference='Conference USA')
        lookup['Louisiana Tech'] = self.add_team(name='Louisiana Tech',conference='Conference USA')
        lookup['Marshall'] = self.add_team(name='Marshall',conference='Conference USA')
        lookup['Middle Tennessee'] = self.add_team(name='Middle Tennessee',conference='Conference USA')
        lookup['North Texas'] = self.add_team(name='North Texas',conference='Conference USA')
        lookup['Rice'] = self.add_team(name='Rice',conference='Conference USA')
        lookup['Southern Miss'] = self.add_team(name='Southern Miss',conference='Conference USA')
        lookup['Texas-El Paso'] = self.add_team(name='Texas-El Paso',conference='Conference USA')
        lookup['Texas-San Antonio'] = self.add_team(name='Texas-San Antonio',conference='Conference USA')
        lookup['Tulane'] = self.add_team(name='Tulane',conference='Conference USA')
        lookup['Tulsa'] = self.add_team(name='Tulsa',conference='Conference USA')
        lookup['UAB'] = self.add_team(name='UAB',conference='Conference USA')
        lookup['Army'] = self.add_team(name='Army',conference='Independents')
        lookup['BYU'] = self.add_team(name='BYU',conference='Independents')
        lookup['Idaho'] = self.add_team(name='Idaho',conference='Independents')
        lookup['Navy'] = self.add_team(name='Navy',conference='Independents')
        lookup['New Mexico State'] = self.add_team(name='New Mexico State',conference='Independents')
        lookup['Notre Dame'] = self.add_team(name='Notre Dame',conference='Independents')
        lookup['Old Dominion'] = self.add_team(name='Old Dominion',conference='Independents')
        lookup['Akron'] = self.add_team(name='Akron',conference='Mid American')
        lookup['Ball State'] = self.add_team(name='Ball State',conference='Mid American')
        lookup['Bowling Green'] = self.add_team(name='Bowling Green',conference='Mid American')
        lookup['Buffalo'] = self.add_team(name='Buffalo',conference='Mid American')
        lookup['Central Michigan'] = self.add_team(name='Central Michigan',conference='Mid American')
        lookup['Eastern Michigan'] = self.add_team(name='Eastern Michigan',conference='Mid American')
        lookup['Kent State'] = self.add_team(name='Kent State',conference='Mid American')
        lookup['Massachusetts'] = self.add_team(name='Massachusetts',conference='Mid American')
        lookup['Miami-Ohio'] = self.add_team(name='Miami-Ohio',conference='Mid American')
        lookup['Northern Illinois'] = self.add_team(name='Northern Illinois',conference='Mid American')
        lookup['Ohio'] = self.add_team(name='Ohio',conference='Mid American')
        lookup['Toledo'] = self.add_team(name='Toledo',conference='Mid American')
        lookup['Western Michigan'] = self.add_team(name='Western Michigan',conference='Mid American')
        lookup['Boise State'] = self.add_team(name='Boise State',conference='Mountain West')
        lookup['Colorado State'] = self.add_team(name='Colorado State',conference='Mountain West')
        lookup['Utah State'] = self.add_team(name='Utah State',conference='Mountain West')
        lookup['Air Force'] = self.add_team(name='Air Force',conference='Mountain West')
        lookup['Fresno State'] = self.add_team(name='Fresno State',conference='Mountain West')
        lookup['Hawaii'] = self.add_team(name='Hawaii',conference='Mountain West')
        lookup['Nevada'] = self.add_team(name='Nevada',conference='Mountain West')
        lookup['New Mexico'] = self.add_team(name='New Mexico',conference='Mountain West')
        lookup['San Diego State'] = self.add_team(name='San Diego State',conference='Mountain West')
        lookup['San Jose State'] = self.add_team(name='San Jose State',conference='Mountain West')
        lookup['UNLV'] = self.add_team(name='UNLV',conference='Mountain West')
        lookup['Wyoming'] = self.add_team(name='Wyoming',conference='Mountain West')
        lookup['California'] = self.add_team(name='California',conference='Pacific 12')
        lookup['Colorado'] = self.add_team(name='Colorado',conference='Pacific 12')
        lookup['Utah'] = self.add_team(name='Utah',conference='Pacific 12')
        lookup['Washington'] = self.add_team(name='Washington',conference='Pacific 12')
        lookup['Arizona'] = self.add_team(name='Arizona',conference='Pacific 12')
        lookup['Arizona State'] = self.add_team(name='Arizona State',conference='Pacific 12')
        lookup['Oregon'] = self.add_team(name='Oregon',conference='Pacific 12')
        lookup['Oregon State'] = self.add_team(name='Oregon State',conference='Pacific 12')
        lookup['Southern Cal'] = self.add_team(name='Southern Cal',conference='Pacific 12')
        lookup['Stanford'] = self.add_team(name='Stanford',conference='Pacific 12')
        lookup['UCLA'] = self.add_team(name='UCLA',conference='Pacific 12')
        lookup['Washington State'] = self.add_team(name='Washington State',conference='Pacific 12')
        lookup['Georgia'] = self.add_team(name='Georgia',conference='Southeastern')
        lookup['LSU'] = self.add_team(name='LSU',conference='Southeastern')
        lookup['Mississippi State'] = self.add_team(name='Mississippi State',conference='Southeastern')
        lookup['South Carolina'] = self.add_team(name='South Carolina',conference='Southeastern')
        lookup['Alabama'] = self.add_team(name='Alabama',conference='Southeastern')
        lookup['Arkansas'] = self.add_team(name='Arkansas',conference='Southeastern')
        lookup['Auburn'] = self.add_team(name='Auburn',conference='Southeastern')
        lookup['Florida'] = self.add_team(name='Florida',conference='Southeastern')
        lookup['Kentucky'] = self.add_team(name='Kentucky',conference='Southeastern')
        lookup['Mississippi'] = self.add_team(name='Mississippi',conference='Southeastern')
        lookup['Missouri'] = self.add_team(name='Missouri',conference='Southeastern')
        lookup['Tennessee'] = self.add_team(name='Tennessee',conference='Southeastern')
        lookup['Texas A&M'] = self.add_team(name='Texas A&M',conference='Southeastern')
        lookup['Vanderbilt'] = self.add_team(name='Vanderbilt',conference='Southeastern')
        lookup['Arkansas State'] = self.add_team(name='Arkansas State',conference='Sun Belt')
        lookup['Georgia State'] = self.add_team(name='Georgia State',conference='Sun Belt')
        lookup['Louisiana Lafayette'] = self.add_team(name='Louisiana Lafayette',conference='Sun Belt')
        lookup['Louisiana Monroe'] = self.add_team(name='Louisiana Monroe',conference='Sun Belt')
        lookup['South Alabama'] = self.add_team(name='South Alabama',conference='Sun Belt')
        lookup['Texas State'] = self.add_team(name='Texas State',conference='Sun Belt')
        lookup['Troy'] = self.add_team(name='Troy',conference='Sun Belt')
        lookup['Western Kentucky'] = self.add_team(name='Western Kentucky',conference='Sun Belt')
        lookup['Cal Poly'] = self.add_team(name='Cal Poly',conference='Big Sky')
        lookup['Eastern Washington'] = self.add_team(name='Eastern Washington',conference='Big Sky')
        lookup['Idaho State'] = self.add_team(name='Idaho State',conference='Big Sky')
        lookup['Montana'] = self.add_team(name='Montana',conference='Big Sky')
        lookup['Montana State'] = self.add_team(name='Montana State',conference='Big Sky')
        lookup['North Dakota'] = self.add_team(name='North Dakota',conference='Big Sky')
        lookup['Northern Arizona'] = self.add_team(name='Northern Arizona',conference='Big Sky')
        lookup['Northern Colorado'] = self.add_team(name='Northern Colorado',conference='Big Sky')
        lookup['Portland State'] = self.add_team(name='Portland State',conference='Big Sky')
        lookup['Sacramento State'] = self.add_team(name='Sacramento State',conference='Big Sky')
        lookup['Southern Utah'] = self.add_team(name='Southern Utah',conference='Big Sky')
        lookup['UC Davis'] = self.add_team(name='UC Davis',conference='Big Sky')
        lookup['Weber State'] = self.add_team(name='Weber State',conference='Big Sky')
        lookup['Charleston Southern'] = self.add_team(name='Charleston Southern',conference='Big South')
        lookup['Coastal Carolina'] = self.add_team(name='Coastal Carolina',conference='Big South')
        lookup['Gardner-Webb'] = self.add_team(name='Gardner-Webb',conference='Big South')
        lookup['Liberty'] = self.add_team(name='Liberty',conference='Big South')
        lookup['Presbyterian'] = self.add_team(name='Presbyterian',conference='Big South')
        lookup['Virginia Military Institute'] = self.add_team(name='Virginia Military Institute',conference='Big South')
        lookup['Albany'] = self.add_team(name='Albany',conference='CAA')
        lookup['Delaware'] = self.add_team(name='Delaware',conference='CAA')
        lookup['James Madison'] = self.add_team(name='James Madison',conference='CAA')
        lookup['Maine'] = self.add_team(name='Maine',conference='CAA')
        lookup['New Hampshire'] = self.add_team(name='New Hampshire',conference='CAA')
        lookup['Rhode Island'] = self.add_team(name='Rhode Island',conference='CAA')
        lookup['Richmond'] = self.add_team(name='Richmond',conference='CAA')
        lookup['Stony Brook'] = self.add_team(name='Stony Brook',conference='CAA')
        lookup['Towson'] = self.add_team(name='Towson',conference='CAA')
        lookup['Villanova'] = self.add_team(name='Villanova',conference='CAA')
        lookup['William & Mary'] = self.add_team(name='William & Mary',conference='CAA')
        lookup['Abilene Christian'] = self.add_team(name='Abilene Christian',conference='FCS Independents')
        lookup['Charlotte'] = self.add_team(name='Charlotte',conference='FCS Independents')
        lookup['Houston Baptist'] = self.add_team(name='Houston Baptist',conference='FCS Independents')
        lookup['Incarnate Word'] = self.add_team(name='Incarnate Word',conference='FCS Independents')
        lookup['Monmouth'] = self.add_team(name='Monmouth',conference='FCS Independents')
        lookup['Brown'] = self.add_team(name='Brown',conference='Ivy')
        lookup['Columbia'] = self.add_team(name='Columbia',conference='Ivy')
        lookup['Cornell'] = self.add_team(name='Cornell',conference='Ivy')
        lookup['Dartmouth'] = self.add_team(name='Dartmouth',conference='Ivy')
        lookup['Harvard'] = self.add_team(name='Harvard',conference='Ivy')
        lookup['Pennsylvania'] = self.add_team(name='Pennsylvania',conference='Ivy')
        lookup['Princeton'] = self.add_team(name='Princeton',conference='Ivy')
        lookup['Yale'] = self.add_team(name='Yale',conference='Ivy')
        lookup['Bethune-Cookman'] = self.add_team(name='Bethune-Cookman',conference='MEAC')
        lookup['Delaware State'] = self.add_team(name='Delaware State',conference='MEAC')
        lookup['Florida A&M'] = self.add_team(name='Florida A&M',conference='MEAC')
        lookup['Hampton'] = self.add_team(name='Hampton',conference='MEAC')
        lookup['Howard'] = self.add_team(name='Howard',conference='MEAC')
        lookup['Morgan State'] = self.add_team(name='Morgan State',conference='MEAC')
        lookup['NC Central'] = self.add_team(name='NC Central',conference='MEAC')
        lookup['Norfolk State'] = self.add_team(name='Norfolk State',conference='MEAC')
        lookup['North Carolina A&T'] = self.add_team(name='North Carolina A&T',conference='MEAC')
        lookup['Savannah State'] = self.add_team(name='Savannah State',conference='MEAC')
        lookup['South Carolina State'] = self.add_team(name='South Carolina State',conference='MEAC')
        lookup['Illinois State'] = self.add_team(name='Illinois State',conference='Missouri Valley')
        lookup['Indiana State'] = self.add_team(name='Indiana State',conference='Missouri Valley')
        lookup['Missouri State'] = self.add_team(name='Missouri State',conference='Missouri Valley')
        lookup['North Dakota State'] = self.add_team(name='North Dakota State',conference='Missouri Valley')
        lookup['Northern Iowa'] = self.add_team(name='Northern Iowa',conference='Missouri Valley')
        lookup['South Dakota'] = self.add_team(name='South Dakota',conference='Missouri Valley')
        lookup['South Dakota State'] = self.add_team(name='South Dakota State',conference='Missouri Valley')
        lookup['Southern Illinois'] = self.add_team(name='Southern Illinois',conference='Missouri Valley')
        lookup['Western Illinois'] = self.add_team(name='Western Illinois',conference='Missouri Valley')
        lookup['Youngstown State'] = self.add_team(name='Youngstown State',conference='Missouri Valley')
        lookup['Bryant'] = self.add_team(name='Bryant',conference='Northeast')
        lookup['Central Connecticut State'] = self.add_team(name='Central Connecticut State',conference='Northeast')
        lookup['Duquesne'] = self.add_team(name='Duquesne',conference='Northeast')
        lookup['Robert Morris'] = self.add_team(name='Robert Morris',conference='Northeast')
        lookup['Sacred Heart'] = self.add_team(name='Sacred Heart',conference='Northeast')
        lookup['St. Francis (PA)'] = self.add_team(name='St. Francis (PA)',conference='Northeast')
        lookup['Wagner'] = self.add_team(name='Wagner',conference='Northeast')
        lookup['Austin Peay'] = self.add_team(name='Austin Peay',conference='Ohio Valley')
        lookup['Eastern Illinois'] = self.add_team(name='Eastern Illinois',conference='Ohio Valley')
        lookup['Eastern Kentucky'] = self.add_team(name='Eastern Kentucky',conference='Ohio Valley')
        lookup['Jacksonville State'] = self.add_team(name='Jacksonville State',conference='Ohio Valley')
        lookup['Murray State'] = self.add_team(name='Murray State',conference='Ohio Valley')
        lookup['Southeast Missouri State'] = self.add_team(name='Southeast Missouri State',conference='Ohio Valley')
        lookup['Tennessee State'] = self.add_team(name='Tennessee State',conference='Ohio Valley')
        lookup['Tennessee Tech'] = self.add_team(name='Tennessee Tech',conference='Ohio Valley')
        lookup['Tennessee-Martin'] = self.add_team(name='Tennessee-Martin',conference='Ohio Valley')
        lookup['Bucknell'] = self.add_team(name='Bucknell',conference='Patriot League')
        lookup['Colgate'] = self.add_team(name='Colgate',conference='Patriot League')
        lookup['Fordham'] = self.add_team(name='Fordham',conference='Patriot League')
        lookup['Georgetown'] = self.add_team(name='Georgetown',conference='Patriot League')
        lookup['Holy Cross'] = self.add_team(name='Holy Cross',conference='Patriot League')
        lookup['Lafayette'] = self.add_team(name='Lafayette',conference='Patriot League')
        lookup['Lehigh'] = self.add_team(name='Lehigh',conference='Patriot League')
        lookup['Butler'] = self.add_team(name='Butler',conference='Pioneer')
        lookup['Campbell'] = self.add_team(name='Campbell',conference='Pioneer')
        lookup['Davidson'] = self.add_team(name='Davidson',conference='Pioneer')
        lookup['Dayton'] = self.add_team(name='Dayton',conference='Pioneer')
        lookup['Drake'] = self.add_team(name='Drake',conference='Pioneer')
        lookup['Jacksonville'] = self.add_team(name='Jacksonville',conference='Pioneer')
        lookup['Marist'] = self.add_team(name='Marist',conference='Pioneer')
        lookup['Mercer'] = self.add_team(name='Mercer',conference='Pioneer')
        lookup['Morehead State'] = self.add_team(name='Morehead State',conference='Pioneer')
        lookup['San Diego'] = self.add_team(name='San Diego',conference='Pioneer')
        lookup['Stetson'] = self.add_team(name='Stetson',conference='Pioneer')
        lookup['Valparaiso'] = self.add_team(name='Valparaiso',conference='Pioneer')
        lookup['Appalachian State'] = self.add_team(name='Appalachian State',conference='Southern')
        lookup['Chattanooga'] = self.add_team(name='Chattanooga',conference='Southern')
        lookup['Citadel'] = self.add_team(name='Citadel',conference='Southern')
        lookup['Elon'] = self.add_team(name='Elon',conference='Southern')
        lookup['Furman'] = self.add_team(name='Furman',conference='Southern')
        lookup['Georgia Southern'] = self.add_team(name='Georgia Southern',conference='Southern')
        lookup['Samford'] = self.add_team(name='Samford',conference='Southern')
        lookup['Western Carolina'] = self.add_team(name='Western Carolina',conference='Southern')
        lookup['Wofford'] = self.add_team(name='Wofford',conference='Southern')
        lookup['Central Arkansas'] = self.add_team(name='Central Arkansas',conference='Southland')
        lookup['Lamar'] = self.add_team(name='Lamar',conference='Southland')
        lookup['McNeese State'] = self.add_team(name='McNeese State',conference='Southland')
        lookup['Nicholls State'] = self.add_team(name='Nicholls State',conference='Southland')
        lookup['Northwestern State'] = self.add_team(name='Northwestern State',conference='Southland')
        lookup['Sam Houston State'] = self.add_team(name='Sam Houston State',conference='Southland')
        lookup['Southeastern Louisiana'] = self.add_team(name='Southeastern Louisiana',conference='Southland')
        lookup['Stephen F. Austin'] = self.add_team(name='Stephen F. Austin',conference='Southland')
        lookup['Alabama A&M'] = self.add_team(name='Alabama A&M',conference='SWAC')
        lookup['Alabama State'] = self.add_team(name='Alabama State',conference='SWAC')
        lookup['Alcorn State'] = self.add_team(name='Alcorn State',conference='SWAC')
        lookup['Arkansas-Pine Bluff'] = self.add_team(name='Arkansas-Pine Bluff',conference='SWAC')
        lookup['Grambling State'] = self.add_team(name='Grambling State',conference='SWAC')
        lookup['Jackson State'] = self.add_team(name='Jackson State',conference='SWAC')
        lookup['Mississippi Valley State'] = self.add_team(name='Mississippi Valley State',conference='SWAC')
        lookup['Prairie View A&M'] = self.add_team(name='Prairie View A&M',conference='SWAC')
        lookup['Southern University'] = self.add_team(name='Southern University',conference='SWAC')
        lookup['Texas Southern'] = self.add_team(name='Texas Southern',conference='SWAC')
        return lookup


