from players import *

class LoadPlayers:

    def add_player(self,name,year):
        p = Player(name=name,year=year)
        return p.put()

    def load(self):
        lookup = dict()
        lookup[1] = self.add_player(name='Jeffrey S.',year=2012)
        lookup[2] = self.add_player(name='Adam S.',year=2012)
        lookup[3] = self.add_player(name='David R.',year=2012)
        lookup[4] = self.add_player(name='Thai N.',year=2012)
        lookup[5] = self.add_player(name='Dale R.',year=2012)
        lookup[6] = self.add_player(name='Amos C.',year=2012)
        lookup[7] = self.add_player(name='Landon A.',year=2012)
        lookup[8] = self.add_player(name='Scott D.',year=2012)
        lookup[9] = self.add_player(name='Jerome B.',year=2012)
        lookup[10] = self.add_player(name='Adam G.',year=2012)
        lookup[11] = self.add_player(name='David B.',year=2012)
        lookup[12] = self.add_player(name='Chris F.',year=2012)
        lookup[13] = self.add_player(name='Dave L.',year=2012)
        lookup[14] = self.add_player(name='Kevin F.',year=2012)
        lookup[15] = self.add_player(name='Byron R.',year=2012)
        lookup[16] = self.add_player(name='Kevin S.',year=2012)
        lookup[17] = self.add_player(name='Chris C.',year=2012)
        lookup[18] = self.add_player(name='Christopher E.',year=2012)
        lookup[19] = self.add_player(name='Martin B.',year=2012)
        lookup[20] = self.add_player(name='Simon C.',year=2012)
        lookup[21] = self.add_player(name='Scott Fe.',year=2012)
        lookup[22] = self.add_player(name='Charles N.',year=2012)
        lookup[23] = self.add_player(name='Tim P.',year=2012)
        lookup[24] = self.add_player(name='David S.',year=2012)
        lookup[25] = self.add_player(name='Daniel D.',year=2012)
        lookup[26] = self.add_player(name='LaMar P.',year=2012)
        lookup[27] = self.add_player(name='Chip A.',year=2012)
        lookup[28] = self.add_player(name='Brent H.',year=2012)
        lookup[29] = self.add_player(name='Larry J.',year=2012)
        lookup[30] = self.add_player(name='Matt H.',year=2012)
        lookup[31] = self.add_player(name='Steve M.',year=2012)
        lookup[32] = self.add_player(name='William M.',year=2012)
        lookup[33] = self.add_player(name='Michael N.',year=2012)
        lookup[34] = self.add_player(name='Todd W.',year=2012)
        lookup[35] = self.add_player(name='Steve W.',year=2012)
        lookup[36] = self.add_player(name='Carlos E.',year=2012)
        lookup[37] = self.add_player(name='Leslie F.',year=2012)
        lookup[38] = self.add_player(name='Robert J.',year=2012)
        lookup[39] = self.add_player(name='Nick E.',year=2012)
        lookup[40] = self.add_player(name='Brandon G.',year=2012)
        lookup[41] = self.add_player(name='Jason H.',year=2012)
        lookup[42] = self.add_player(name='Chris R.',year=2012)
        lookup[43] = self.add_player(name='Brantley B.',year=2012)
        lookup[44] = self.add_player(name='Douglas M.',year=2012)
        lookup[45] = self.add_player(name='Kevin M.',year=2012)
        lookup[46] = self.add_player(name='Moises P.',year=2012)
        lookup[47] = self.add_player(name='Brooker S.',year=2012)
        lookup[48] = self.add_player(name='Jarred W.',year=2012)
        lookup[49] = self.add_player(name='Kenneth Y.',year=2012)
        lookup[50] = self.add_player(name='Van S.',year=2012)
        lookup[51] = self.add_player(name='Carl S.',year=2012)
        lookup[52] = self.add_player(name='Greg I.',year=2012)
        lookup[53] = self.add_player(name='Seth W.',year=2012)
        lookup[54] = self.add_player(name='Rob N.',year=2012)
        lookup[55] = self.add_player(name='Marwan K.',year=2012)
        lookup[56] = self.add_player(name='Jeffrey S.',year=2013)
        lookup[57] = self.add_player(name='Brandon G.',year=2013)
        lookup[58] = self.add_player(name='Alexander M.',year=2013)
        lookup[59] = self.add_player(name='Amos C.',year=2013)
        lookup[60] = self.add_player(name='Larry J.',year=2013)
        lookup[61] = self.add_player(name='Thai N.',year=2013)
        lookup[62] = self.add_player(name='Simon C.',year=2013)
        lookup[63] = self.add_player(name='Van S.',year=2013)
        lookup[64] = self.add_player(name='Nick E.',year=2013)
        lookup[65] = self.add_player(name='Amber N.',year=2013)
        lookup[66] = self.add_player(name='David S.',year=2013)
        lookup[67] = self.add_player(name='Steve W.',year=2013)
        lookup[68] = self.add_player(name='Chris F.',year=2013)
        lookup[69] = self.add_player(name='Kevin M.',year=2013)
        lookup[70] = self.add_player(name='David B.',year=2013)
        lookup[71] = self.add_player(name='Daniel D.',year=2013)
        lookup[72] = self.add_player(name='Scott Fe.',year=2013)
        lookup[73] = self.add_player(name='Greg I.',year=2013)
        lookup[74] = self.add_player(name='Byron R.',year=2013)
        lookup[75] = self.add_player(name='Matt H.',year=2013)
        lookup[76] = self.add_player(name='Brent H.',year=2013)
        lookup[77] = self.add_player(name='Dave L.',year=2013)
        lookup[78] = self.add_player(name='William M.',year=2013)
        lookup[79] = self.add_player(name='Jarred W.',year=2013)
        lookup[80] = self.add_player(name='Chip A.',year=2013)
        lookup[81] = self.add_player(name='Christopher E.',year=2013)
        lookup[82] = self.add_player(name='Kevin F.',year=2013)
        lookup[83] = self.add_player(name='Michael N.',year=2013)
        lookup[84] = self.add_player(name='Charles N.',year=2013)
        lookup[85] = self.add_player(name='Kevin S.',year=2013)
        lookup[86] = self.add_player(name='Steve M.',year=2013)
        lookup[87] = self.add_player(name='Adam S.',year=2013)
        lookup[88] = self.add_player(name='Leslie F.',year=2013)
        lookup[89] = self.add_player(name='Jeremy H.',year=2013)
        lookup[90] = self.add_player(name='Robert J.',year=2013)
        lookup[91] = self.add_player(name='Douglas M.',year=2013)
        lookup[92] = self.add_player(name='Aaron P.',year=2013)
        lookup[93] = self.add_player(name='Dale R.',year=2013)
        lookup[94] = self.add_player(name='Scott D.',year=2013)
        lookup[95] = self.add_player(name='Adam G.',year=2013)
        lookup[96] = self.add_player(name='Tim P.',year=2013)
        lookup[97] = self.add_player(name='Chris R.',year=2013)
        lookup[98] = self.add_player(name='Carl S.',year=2013)
        lookup[99] = self.add_player(name='Kenneth Y.',year=2013)
        lookup[100] = self.add_player(name='Martin B.',year=2013)
        lookup[101] = self.add_player(name='Chris C.',year=2013)
        lookup[102] = self.add_player(name='Landon A.',year=2013)
        lookup[103] = self.add_player(name='Jerome B.',year=2013)
        lookup[104] = self.add_player(name='William C.',year=2013)
        lookup[105] = self.add_player(name='David R.',year=2013)
        lookup[106] = self.add_player(name='Seth W.',year=2013)
        lookup[107] = self.add_player(name='LaMar P.',year=2013)
        lookup[108] = self.add_player(name='Scott Fr.',year=2013)
        lookup[109] = self.add_player(name='Moises P.',year=2013)
        lookup[110] = self.add_player(name='Rob N.',year=2013)
        return lookup


